"""Freeze the baseline schema, so migration drift can actually be detected.

THE PROBLEM THIS SOLVES
-----------------------
`0001_baseline` is an empty anchor: its `upgrade()` is `pass`, because when
Alembic was adopted the production database already had the schema and stamping
it had to cost nothing. A real consequence follows that is easy to miss —

    THE MIGRATION TREE CANNOT BUILD A DATABASE FROM NOTHING.

`migrate.py` handles that by running `create_all()` first on an empty database,
then stamping. Which means the obvious drift check —

    fresh database -> migrate -> autogenerate diff against models.py

is worthless: `create_all()` builds the schema FROM models.py, so it is
comparing the models against themselves and returns an empty diff no matter how
badly the migrations lag. The first version of the CI gate did exactly that.

WHAT THIS DOES INSTEAD
----------------------
Captures the CURRENT model shape once, as checked-in SQL. CI then builds a
database from that FROZEN file — not from models.py — stamps the baseline,
runs every migration, and compares the result to models.py. Now:

    model column added WITH a migration    -> the migration adds it  -> no diff
    model column added WITHOUT a migration -> nothing adds it        -> DIFF

which is #513, caught before merge.

It also happens to rehearse production's real upgrade path on every CI run: a
pre-existing schema, stamped at the baseline, migrated forward.

WHEN TO REGENERATE
------------------
Almost never. The snapshot is a fixed historical point, not a mirror of the
models — regenerating it after adding a column would erase exactly the evidence
the gate depends on. Regenerate only when deliberately re-baselining (squashing
the migration history), and say so in the commit.

    python backend/snapshot_baseline.py            # rewrite the snapshot
    python backend/snapshot_baseline.py --check    # is it still applicable?
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SNAPSHOT = os.path.join(HERE, "alembic", "baseline_schema.sql")

HEADER = """-- THE BASELINE SCHEMA, FROZEN. Generated by snapshot_baseline.py.
--
-- This is the shape the database had when the migration-drift gate was
-- introduced (ADR-0018). CI builds a database from THIS FILE, stamps
-- 0001_baseline, runs every migration, and requires the result to match
-- models.py exactly.
--
-- DO NOT regenerate it to make a failing build pass. A diff means a model was
-- changed without a migration -- write the migration. Regenerating erases the
-- evidence, and that is the #513 failure class walking back in through the
-- door marked "fix the test".
--
-- Regenerate ONLY when deliberately re-baselining the migration history.
"""


def render():
    """Emit CREATE TABLE / CREATE INDEX for every mapped table, PostgreSQL dialect."""
    from sqlalchemy.schema import CreateIndex, CreateTable
    from sqlalchemy.dialects import postgresql

    import models  # noqa: F401  (registers every table on the metadata)
    from database import Base

    dialect = postgresql.dialect()
    out = [HEADER]
    # sorted_tables resolves foreign-key order, so the file applies top to bottom.
    for table in Base.metadata.sorted_tables:
        out.append(str(CreateTable(table).compile(dialect=dialect)).strip() + ";")
        for index in sorted(table.indexes, key=lambda i: i.name or ""):
            out.append(str(CreateIndex(index).compile(dialect=dialect)).strip() + ";")
    return "\n\n".join(out) + "\n"


def write():
    sql = render()
    with open(SNAPSHOT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(sql)
    tables = sql.count("CREATE TABLE")
    print(f"wrote {SNAPSHOT} ({tables} tables)")
    return 0


def check():
    """The snapshot must exist and be non-trivial. It is deliberately NOT
    compared against the current models: they are expected to diverge the moment
    a migration is written, and that divergence is the whole signal."""
    if not os.path.exists(SNAPSHOT):
        print("MISSING: run python backend/snapshot_baseline.py")
        return 1
    body = open(SNAPSHOT, encoding="utf-8").read()
    tables = body.count("CREATE TABLE")
    if tables < 40:
        print(f"SUSPECT: only {tables} tables in the snapshot")
        return 1
    print(f"snapshot present ({tables} tables)")
    return 0


if __name__ == "__main__":
    sys.exit(check() if "--check" in sys.argv else write())
