-- THE BASELINE SCHEMA, FROZEN. Generated by snapshot_baseline.py.
--
-- This is the shape the database had when the migration-drift gate was
-- introduced (ADR-0018). CI builds a database from THIS FILE, stamps
-- 0001_baseline, runs every migration, and requires the result to match
-- models.py exactly.
--
-- DO NOT regenerate it to make a failing build pass. A diff means a model was
-- changed without a migration -- write the migration. Regenerating erases the
-- evidence, and that is the #513 failure class walking back in through the
-- door marked "fix the test".
--
-- Regenerate ONLY when deliberately re-baselining the migration history.


CREATE TABLE agent_actions (
	id SERIAL NOT NULL, 
	tenant_code VARCHAR NOT NULL, 
	agent VARCHAR NOT NULL, 
	action_type VARCHAR NOT NULL, 
	summary VARCHAR NOT NULL, 
	ref_kind VARCHAR NOT NULL, 
	ref_id INTEGER, 
	severity VARCHAR, 
	status VARCHAR, 
	related_machine_id INTEGER, 
	decided_by VARCHAR, 
	decided_at TIMESTAMP WITHOUT TIME ZONE, 
	expires_at TIMESTAMP WITHOUT TIME ZONE, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id)
);

CREATE INDEX ix_agent_actions_created_at ON agent_actions (created_at);

CREATE INDEX ix_agent_actions_id ON agent_actions (id);

CREATE INDEX ix_agent_actions_tenant_code ON agent_actions (tenant_code);

CREATE TABLE agent_policies (
	id SERIAL NOT NULL, 
	tenant_code VARCHAR NOT NULL, 
	auto_approve_agents VARCHAR, 
	updated_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id)
);

CREATE INDEX ix_agent_policies_id ON agent_policies (id);

CREATE UNIQUE INDEX ix_agent_policies_tenant_code ON agent_policies (tenant_code);

CREATE TABLE alerts (
	id SERIAL NOT NULL, 
	tenant_code VARCHAR NOT NULL, 
	alert_type VARCHAR NOT NULL, 
	severity VARCHAR NOT NULL, 
	message VARCHAR NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id)
);

CREATE INDEX ix_alerts_id ON alerts (id);

CREATE INDEX ix_alerts_tenant_code ON alerts (tenant_code);

CREATE TABLE audit_logs (
	id SERIAL NOT NULL, 
	tenant_code VARCHAR, 
	actor VARCHAR, 
	action VARCHAR NOT NULL, 
	entity_type VARCHAR, 
	entity_id INTEGER, 
	details VARCHAR, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id)
);

CREATE INDEX ix_audit_logs_id ON audit_logs (id);

CREATE INDEX ix_audit_logs_tenant_code ON audit_logs (tenant_code);

CREATE TABLE bills_of_materials (
	id SERIAL NOT NULL, 
	tenant_code VARCHAR NOT NULL, 
	part_number VARCHAR NOT NULL, 
	revision VARCHAR NOT NULL, 
	output_item_code VARCHAR, 
	effective_from DATE, 
	active BOOLEAN NOT NULL, 
	notes TEXT, 
	created_by VARCHAR, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	updated_by VARCHAR, 
	updated_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_bom_tenant_part_revision UNIQUE (tenant_code, part_number, revision)
);

CREATE INDEX ix_bills_of_materials_id ON bills_of_materials (id);

CREATE INDEX ix_bills_of_materials_tenant_code ON bills_of_materials (tenant_code);

CREATE TABLE company_tenants (
	id SERIAL NOT NULL, 
	company_code VARCHAR NOT NULL, 
	company_name VARCHAR NOT NULL, 
	industry VARCHAR, 
	plan_name VARCHAR, 
	subscription_status VARCHAR, 
	seats INTEGER, 
	monthly_fee INTEGER, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	UNIQUE (company_code)
);

CREATE INDEX ix_company_tenants_id ON company_tenants (id);

CREATE TABLE compliance_documents (
	id SERIAL NOT NULL, 
	tenant_code VARCHAR NOT NULL, 
	document_no VARCHAR NOT NULL, 
	title VARCHAR NOT NULL, 
	document_type VARCHAR NOT NULL, 
	department VARCHAR NOT NULL, 
	version VARCHAR, 
	owner VARCHAR NOT NULL, 
	approval_status VARCHAR, 
	review_due_date DATE NOT NULL, 
	storage_link VARCHAR, 
	notes VARCHAR, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_compliance_documents_tenant_document_no UNIQUE (tenant_code, document_no)
);

CREATE INDEX ix_compliance_documents_id ON compliance_documents (id);

CREATE INDEX ix_compliance_documents_tenant_code ON compliance_documents (tenant_code);

CREATE TABLE cost_records (
	id SERIAL NOT NULL, 
	tenant_code VARCHAR NOT NULL, 
	cost_no VARCHAR NOT NULL, 
	cost_type VARCHAR NOT NULL, 
	reference_type VARCHAR, 
	reference_id INTEGER, 
	description VARCHAR NOT NULL, 
	amount INTEGER, 
	department VARCHAR, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_cost_records_tenant_cost_no UNIQUE (tenant_code, cost_no)
);

CREATE INDEX ix_cost_records_created_at ON cost_records (created_at);

CREATE INDEX ix_cost_records_id ON cost_records (id);

CREATE INDEX ix_cost_records_tenant_code ON cost_records (tenant_code);

CREATE TABLE cycle_counts (
	id SERIAL NOT NULL, 
	tenant_code VARCHAR, 
	count_no VARCHAR NOT NULL, 
	counted_by VARCHAR NOT NULL, 
	status VARCHAR, 
	notes VARCHAR, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_cycle_counts_tenant_count_no UNIQUE (tenant_code, count_no)
);

CREATE INDEX ix_cycle_counts_id ON cycle_counts (id);

CREATE INDEX ix_cycle_counts_tenant_code ON cycle_counts (tenant_code);

CREATE TABLE document_sequences (
	id SERIAL NOT NULL, 
	tenant_code VARCHAR NOT NULL, 
	doc_type VARCHAR NOT NULL, 
	next_value INTEGER NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_document_sequences_tenant_type UNIQUE (tenant_code, doc_type)
);

CREATE INDEX ix_document_sequences_id ON document_sequences (id);

CREATE INDEX ix_document_sequences_tenant_code ON document_sequences (tenant_code);

CREATE TABLE event_log (
	id SERIAL NOT NULL, 
	tenant_code VARCHAR NOT NULL, 
	event_type VARCHAR NOT NULL, 
	event_version INTEGER, 
	payload TEXT, 
	occurred_at TIMESTAMP WITHOUT TIME ZONE, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id)
);

CREATE INDEX ix_event_log_event_type ON event_log (event_type);

CREATE INDEX ix_event_log_id ON event_log (id);

CREATE INDEX ix_event_log_occurred_at ON event_log (occurred_at);

CREATE INDEX ix_event_log_tenant_code ON event_log (tenant_code);

CREATE TABLE gmats_items (
	id SERIAL NOT NULL, 
	tenant_code VARCHAR, 
	item_code VARCHAR NOT NULL, 
	item_name VARCHAR NOT NULL, 
	category VARCHAR, 
	unit VARCHAR, 
	physical_stock INTEGER, 
	reserved_stock INTEGER, 
	reorder_level INTEGER, 
	location VARCHAR, 
	purchase_rate INTEGER, 
	supplier VARCHAR, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id)
);

CREATE INDEX ix_gmats_items_id ON gmats_items (id);

CREATE INDEX ix_gmats_items_tenant_code ON gmats_items (tenant_code);

CREATE TABLE gmats_min (
	id SERIAL NOT NULL, 
	tenant_code VARCHAR, 
	min_no VARCHAR NOT NULL, 
	customer_name VARCHAR NOT NULL, 
	machine_ref VARCHAR, 
	status VARCHAR, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id)
);

CREATE INDEX ix_gmats_min_id ON gmats_min (id);

CREATE INDEX ix_gmats_min_tenant_code ON gmats_min (tenant_code);

CREATE TABLE gmats_proformas (
	id SERIAL NOT NULL, 
	tenant_code VARCHAR, 
	proforma_no VARCHAR NOT NULL, 
	customer_name VARCHAR NOT NULL, 
	status VARCHAR, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id)
);

CREATE INDEX ix_gmats_proformas_id ON gmats_proformas (id);

CREATE INDEX ix_gmats_proformas_tenant_code ON gmats_proformas (tenant_code);

CREATE TABLE goods_receipt_notes (
	id SERIAL NOT NULL, 
	tenant_code VARCHAR, 
	grn_no VARCHAR NOT NULL, 
	purchase_order_ref VARCHAR, 
	supplier_name VARCHAR NOT NULL, 
	received_by VARCHAR NOT NULL, 
	status VARCHAR, 
	notes VARCHAR, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_goods_receipt_notes_tenant_grn_no UNIQUE (tenant_code, grn_no)
);

CREATE INDEX ix_goods_receipt_notes_id ON goods_receipt_notes (id);

CREATE INDEX ix_goods_receipt_notes_tenant_code ON goods_receipt_notes (tenant_code);

CREATE TABLE inventory_items (
	id SERIAL NOT NULL, 
	tenant_code VARCHAR NOT NULL, 
	item_code VARCHAR NOT NULL, 
	item_name VARCHAR NOT NULL, 
	category VARCHAR NOT NULL, 
	supplier VARCHAR, 
	unit VARCHAR NOT NULL, 
	current_stock INTEGER, 
	reorder_level INTEGER, 
	location VARCHAR, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_inventory_items_tenant_item_code UNIQUE (tenant_code, item_code)
);

CREATE INDEX ix_inventory_items_id ON inventory_items (id);

CREATE INDEX ix_inventory_items_tenant_code ON inventory_items (tenant_code);

CREATE TABLE machine_models (
	id SERIAL NOT NULL, 
	oem_code VARCHAR NOT NULL, 
	family VARCHAR NOT NULL, 
	model_code VARCHAR NOT NULL, 
	name VARCHAR NOT NULL, 
	description TEXT, 
	rated_capacity VARCHAR, 
	rated_capacity_unit VARCHAR, 
	service_interval_hours INTEGER, 
	warranty_months INTEGER, 
	telemetry_profile TEXT, 
	documentation_url VARCHAR, 
	image_url VARCHAR, 
	status VARCHAR NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_machine_model_identity UNIQUE (oem_code, model_code)
);

CREATE INDEX ix_machine_models_id ON machine_models (id);

CREATE INDEX ix_machine_models_oem_code ON machine_models (oem_code);

CREATE TABLE machines (
	id SERIAL NOT NULL, 
	tenant_code VARCHAR NOT NULL, 
	site VARCHAR DEFAULT '' NOT NULL, 
	name VARCHAR NOT NULL, 
	status VARCHAR NOT NULL, 
	utilization INTEGER, 
	downtime VARCHAR, 
	line VARCHAR, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_machine_identity UNIQUE (tenant_code, site, name)
);

CREATE INDEX ix_machines_id ON machines (id);

CREATE INDEX ix_machines_tenant_code ON machines (tenant_code);

CREATE TABLE notifications (
	id SERIAL NOT NULL, 
	tenant_code VARCHAR NOT NULL, 
	notification_type VARCHAR NOT NULL, 
	severity VARCHAR, 
	title VARCHAR NOT NULL, 
	message VARCHAR NOT NULL, 
	status VARCHAR, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id)
);

CREATE INDEX ix_notifications_id ON notifications (id);

CREATE INDEX ix_notifications_tenant_code ON notifications (tenant_code);

CREATE TABLE oem_data_sharing_policies (
	id SERIAL NOT NULL, 
	oem_code VARCHAR NOT NULL, 
	tenant_code VARCHAR NOT NULL, 
	grants VARCHAR NOT NULL, 
	updated_by VARCHAR, 
	updated_at TIMESTAMP WITHOUT TIME ZONE, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_oem_sharing_policy UNIQUE (oem_code, tenant_code)
);

CREATE INDEX ix_oem_data_sharing_policies_id ON oem_data_sharing_policies (id);

CREATE INDEX ix_oem_data_sharing_policies_oem_code ON oem_data_sharing_policies (oem_code);

CREATE INDEX ix_oem_data_sharing_policies_tenant_code ON oem_data_sharing_policies (tenant_code);

CREATE TABLE oem_organizations (
	id SERIAL NOT NULL, 
	oem_code VARCHAR NOT NULL, 
	name VARCHAR NOT NULL, 
	brand_name VARCHAR, 
	brand_color VARCHAR, 
	brand_logo_url VARCHAR, 
	support_email VARCHAR, 
	support_phone VARCHAR, 
	is_active BOOLEAN DEFAULT true NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id)
);

CREATE INDEX ix_oem_organizations_id ON oem_organizations (id);

CREATE UNIQUE INDEX ix_oem_organizations_oem_code ON oem_organizations (oem_code);

CREATE TABLE oem_users (
	id SERIAL NOT NULL, 
	oem_code VARCHAR NOT NULL, 
	username VARCHAR NOT NULL, 
	password VARCHAR NOT NULL, 
	role VARCHAR NOT NULL, 
	is_active BOOLEAN DEFAULT true NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	UNIQUE (username)
);

CREATE INDEX ix_oem_users_id ON oem_users (id);

CREATE INDEX ix_oem_users_oem_code ON oem_users (oem_code);

CREATE TABLE report_requests (
	id SERIAL NOT NULL, 
	tenant_code VARCHAR NOT NULL, 
	report_no VARCHAR NOT NULL, 
	report_type VARCHAR NOT NULL, 
	requested_by VARCHAR, 
	format VARCHAR, 
	status VARCHAR, 
	notes VARCHAR, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_report_requests_tenant_report_no UNIQUE (tenant_code, report_no)
);

CREATE INDEX ix_report_requests_id ON report_requests (id);

CREATE INDEX ix_report_requests_tenant_code ON report_requests (tenant_code);

CREATE TABLE shift_data (
	id SERIAL NOT NULL, 
	tenant_code VARCHAR NOT NULL, 
	shift_name VARCHAR NOT NULL, 
	target_output INTEGER NOT NULL, 
	actual_output INTEGER NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id)
);

CREATE INDEX ix_shift_data_created_at ON shift_data (created_at);

CREATE INDEX ix_shift_data_id ON shift_data (id);

CREATE INDEX ix_shift_data_tenant_code ON shift_data (tenant_code);

CREATE TABLE suppliers (
	id SERIAL NOT NULL, 
	tenant_code VARCHAR NOT NULL, 
	supplier_code VARCHAR NOT NULL, 
	supplier_name VARCHAR NOT NULL, 
	contact_person VARCHAR, 
	email VARCHAR, 
	phone VARCHAR, 
	category VARCHAR, 
	status VARCHAR, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_suppliers_tenant_supplier_code UNIQUE (tenant_code, supplier_code)
);

CREATE INDEX ix_suppliers_id ON suppliers (id);

CREATE INDEX ix_suppliers_tenant_code ON suppliers (tenant_code);

CREATE TABLE tenant_configs (
	id SERIAL NOT NULL, 
	tenant_code VARCHAR NOT NULL, 
	plan VARCHAR, 
	enabled_modules VARCHAR, 
	brand_name VARCHAR, 
	brand_color VARCHAR, 
	brand_logo_url VARCHAR, 
	subscription_status VARCHAR, 
	trial_ends_at TIMESTAMP WITHOUT TIME ZONE, 
	unit_value_gbp FLOAT, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id)
);

CREATE INDEX ix_tenant_configs_id ON tenant_configs (id);

CREATE UNIQUE INDEX ix_tenant_configs_tenant_code ON tenant_configs (tenant_code);

CREATE TABLE users (
	id SERIAL NOT NULL, 
	username VARCHAR NOT NULL, 
	password VARCHAR NOT NULL, 
	role VARCHAR NOT NULL, 
	tenant_code VARCHAR, 
	is_active BOOLEAN DEFAULT true NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (username)
);

CREATE INDEX ix_users_id ON users (id);

CREATE TABLE ai_recommendations (
	id SERIAL NOT NULL, 
	tenant_code VARCHAR NOT NULL, 
	recommendation_type VARCHAR NOT NULL, 
	severity VARCHAR, 
	title VARCHAR NOT NULL, 
	message VARCHAR NOT NULL, 
	related_machine_id INTEGER, 
	confidence INTEGER, 
	status VARCHAR, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	FOREIGN KEY(related_machine_id) REFERENCES machines (id)
);

CREATE INDEX ix_ai_recommendations_id ON ai_recommendations (id);

CREATE INDEX ix_ai_recommendations_tenant_code ON ai_recommendations (tenant_code);

CREATE TABLE bom_components (
	id SERIAL NOT NULL, 
	tenant_code VARCHAR NOT NULL, 
	bom_id INTEGER NOT NULL, 
	component_code VARCHAR NOT NULL, 
	quantity_per_unit FLOAT NOT NULL, 
	unit VARCHAR NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_bom_component UNIQUE (bom_id, component_code), 
	FOREIGN KEY(bom_id) REFERENCES bills_of_materials (id)
);

CREATE INDEX ix_bom_components_bom_id ON bom_components (bom_id);

CREATE INDEX ix_bom_components_id ON bom_components (id);

CREATE INDEX ix_bom_components_tenant_code ON bom_components (tenant_code);

CREATE TABLE cycle_count_items (
	id SERIAL NOT NULL, 
	tenant_code VARCHAR, 
	count_id INTEGER, 
	item_id INTEGER, 
	book_qty INTEGER NOT NULL, 
	physical_qty INTEGER NOT NULL, 
	variance INTEGER NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	FOREIGN KEY(count_id) REFERENCES cycle_counts (id), 
	FOREIGN KEY(item_id) REFERENCES inventory_items (id)
);

CREATE INDEX ix_cycle_count_items_id ON cycle_count_items (id);

CREATE INDEX ix_cycle_count_items_tenant_code ON cycle_count_items (tenant_code);

CREATE TABLE downtime_logs (
	id SERIAL NOT NULL, 
	tenant_code VARCHAR NOT NULL, 
	machine_id INTEGER, 
	reason VARCHAR NOT NULL, 
	duration VARCHAR NOT NULL, 
	notes VARCHAR, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	FOREIGN KEY(machine_id) REFERENCES machines (id)
);

CREATE INDEX ix_downtime_logs_created_at ON downtime_logs (created_at);

CREATE INDEX ix_downtime_logs_id ON downtime_logs (id);

CREATE INDEX ix_downtime_logs_tenant_code ON downtime_logs (tenant_code);

CREATE TABLE escalations (
	id SERIAL NOT NULL, 
	tenant_code VARCHAR NOT NULL, 
	machine_id INTEGER, 
	title VARCHAR NOT NULL, 
	severity VARCHAR NOT NULL, 
	owner VARCHAR NOT NULL, 
	department VARCHAR NOT NULL, 
	status VARCHAR, 
	source VARCHAR, 
	notes VARCHAR, 
	resolution_notes VARCHAR, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	resolved_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	FOREIGN KEY(machine_id) REFERENCES machines (id)
);

CREATE INDEX ix_escalations_id ON escalations (id);

CREATE INDEX ix_escalations_tenant_code ON escalations (tenant_code);

CREATE TABLE factory_layout_nodes (
	id SERIAL NOT NULL, 
	tenant_code VARCHAR NOT NULL, 
	machine_id INTEGER, 
	node_name VARCHAR NOT NULL, 
	node_type VARCHAR, 
	x_position INTEGER, 
	y_position INTEGER, 
	width INTEGER, 
	height INTEGER, 
	zone VARCHAR, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	FOREIGN KEY(machine_id) REFERENCES machines (id)
);

CREATE INDEX ix_factory_layout_nodes_id ON factory_layout_nodes (id);

CREATE INDEX ix_factory_layout_nodes_tenant_code ON factory_layout_nodes (tenant_code);

CREATE TABLE gmats_aliases (
	id SERIAL NOT NULL, 
	tenant_code VARCHAR, 
	item_id INTEGER, 
	alias_name VARCHAR NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	FOREIGN KEY(item_id) REFERENCES gmats_items (id)
);

CREATE INDEX ix_gmats_aliases_id ON gmats_aliases (id);

CREATE INDEX ix_gmats_aliases_tenant_code ON gmats_aliases (tenant_code);

CREATE TABLE gmats_invoices (
	id SERIAL NOT NULL, 
	tenant_code VARCHAR, 
	invoice_no VARCHAR NOT NULL, 
	proforma_id INTEGER, 
	customer_name VARCHAR NOT NULL, 
	status VARCHAR, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	FOREIGN KEY(proforma_id) REFERENCES gmats_proformas (id)
);

CREATE INDEX ix_gmats_invoices_id ON gmats_invoices (id);

CREATE INDEX ix_gmats_invoices_tenant_code ON gmats_invoices (tenant_code);

CREATE TABLE gmats_min_lines (
	id SERIAL NOT NULL, 
	min_id INTEGER, 
	item_id INTEGER, 
	qty INTEGER NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(min_id) REFERENCES gmats_min (id), 
	FOREIGN KEY(item_id) REFERENCES gmats_items (id)
);

CREATE INDEX ix_gmats_min_lines_id ON gmats_min_lines (id);

CREATE TABLE gmats_proforma_lines (
	id SERIAL NOT NULL, 
	proforma_id INTEGER, 
	item_id INTEGER, 
	qty INTEGER NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(proforma_id) REFERENCES gmats_proformas (id), 
	FOREIGN KEY(item_id) REFERENCES gmats_items (id)
);

CREATE INDEX ix_gmats_proforma_lines_id ON gmats_proforma_lines (id);

CREATE TABLE grn_items (
	id SERIAL NOT NULL, 
	tenant_code VARCHAR, 
	grn_id INTEGER, 
	item_id INTEGER, 
	lot_no VARCHAR, 
	ordered_qty INTEGER, 
	received_qty INTEGER NOT NULL, 
	accepted_qty INTEGER NOT NULL, 
	rejected_qty INTEGER, 
	inspection_status VARCHAR, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	FOREIGN KEY(grn_id) REFERENCES goods_receipt_notes (id), 
	FOREIGN KEY(item_id) REFERENCES inventory_items (id)
);

CREATE INDEX ix_grn_items_id ON grn_items (id);

CREATE INDEX ix_grn_items_tenant_code ON grn_items (tenant_code);

CREATE TABLE industrial_devices (
	id SERIAL NOT NULL, 
	tenant_code VARCHAR NOT NULL, 
	device_code VARCHAR NOT NULL, 
	device_name VARCHAR NOT NULL, 
	device_type VARCHAR, 
	protocol VARCHAR, 
	ip_address VARCHAR, 
	topic VARCHAR, 
	linked_machine_id INTEGER, 
	status VARCHAR, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_industrial_devices_tenant_device_code UNIQUE (tenant_code, device_code), 
	FOREIGN KEY(linked_machine_id) REFERENCES machines (id)
);

CREATE INDEX ix_industrial_devices_id ON industrial_devices (id);

CREATE INDEX ix_industrial_devices_tenant_code ON industrial_devices (tenant_code);

CREATE TABLE inventory_transactions (
	id SERIAL NOT NULL, 
	tenant_code VARCHAR NOT NULL, 
	item_id INTEGER, 
	transaction_type VARCHAR NOT NULL, 
	quantity INTEGER NOT NULL, 
	reference VARCHAR, 
	notes VARCHAR, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	FOREIGN KEY(item_id) REFERENCES inventory_items (id)
);

CREATE INDEX ix_inventory_transactions_id ON inventory_transactions (id);

CREATE INDEX ix_inventory_transactions_tenant_code ON inventory_transactions (tenant_code);

CREATE TABLE iot_telemetry (
	id SERIAL NOT NULL, 
	tenant_code VARCHAR NOT NULL, 
	machine_id INTEGER, 
	signal_name VARCHAR NOT NULL, 
	signal_value VARCHAR NOT NULL, 
	numeric_value INTEGER, 
	unit VARCHAR, 
	source VARCHAR, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	FOREIGN KEY(machine_id) REFERENCES machines (id)
);

CREATE INDEX ix_iot_telemetry_id ON iot_telemetry (id);

CREATE INDEX ix_iot_telemetry_tenant_code ON iot_telemetry (tenant_code);

CREATE TABLE machine_events (
	id SERIAL NOT NULL, 
	tenant_code VARCHAR NOT NULL, 
	machine_id INTEGER, 
	machine_name VARCHAR NOT NULL, 
	old_status VARCHAR, 
	new_status VARCHAR NOT NULL, 
	utilization INTEGER, 
	source VARCHAR, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	FOREIGN KEY(machine_id) REFERENCES machines (id)
);

CREATE INDEX ix_machine_events_id ON machine_events (id);

CREATE INDEX ix_machine_events_tenant_code ON machine_events (tenant_code);

CREATE TABLE machine_installations (
	id SERIAL NOT NULL, 
	oem_code VARCHAR NOT NULL, 
	serial_number VARCHAR NOT NULL, 
	model_id INTEGER NOT NULL, 
	factory_tenant_code VARCHAR, 
	site VARCHAR DEFAULT '' NOT NULL, 
	machine_id INTEGER, 
	status VARCHAR NOT NULL, 
	installed_at TIMESTAMP WITHOUT TIME ZONE, 
	commissioned_at TIMESTAMP WITHOUT TIME ZONE, 
	decommissioned_at TIMESTAMP WITHOUT TIME ZONE, 
	warranty_start DATE, 
	warranty_end DATE, 
	operating_hours FLOAT, 
	last_service_hours FLOAT, 
	last_service_at TIMESTAMP WITHOUT TIME ZONE, 
	last_seen_at TIMESTAMP WITHOUT TIME ZONE, 
	firmware_version VARCHAR, 
	notes TEXT, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	updated_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_installation_serial UNIQUE (oem_code, serial_number), 
	FOREIGN KEY(model_id) REFERENCES machine_models (id), 
	FOREIGN KEY(machine_id) REFERENCES machines (id)
);

CREATE INDEX ix_machine_installations_factory_tenant_code ON machine_installations (factory_tenant_code);

CREATE INDEX ix_machine_installations_id ON machine_installations (id);

CREATE INDEX ix_machine_installations_oem_code ON machine_installations (oem_code);

CREATE INDEX ix_machine_installations_serial_number ON machine_installations (serial_number);

CREATE TABLE maintenance_tasks (
	id SERIAL NOT NULL, 
	tenant_code VARCHAR NOT NULL, 
	task_no VARCHAR NOT NULL, 
	machine_id INTEGER, 
	task_type VARCHAR NOT NULL, 
	priority VARCHAR, 
	assigned_to VARCHAR NOT NULL, 
	planned_date DATE NOT NULL, 
	completed_date DATE, 
	downtime_minutes INTEGER, 
	spare_parts_used VARCHAR, 
	status VARCHAR, 
	notes VARCHAR, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_maintenance_tasks_tenant_task_no UNIQUE (tenant_code, task_no), 
	FOREIGN KEY(machine_id) REFERENCES machines (id)
);

CREATE INDEX ix_maintenance_tasks_id ON maintenance_tasks (id);

CREATE INDEX ix_maintenance_tasks_tenant_code ON maintenance_tasks (tenant_code);

CREATE TABLE production_records (
	id SERIAL NOT NULL, 
	tenant_code VARCHAR NOT NULL, 
	machine_id INTEGER, 
	planned_minutes INTEGER NOT NULL, 
	runtime_minutes INTEGER NOT NULL, 
	ideal_cycle_time_seconds INTEGER NOT NULL, 
	total_count INTEGER NOT NULL, 
	good_count INTEGER NOT NULL, 
	rejected_count INTEGER NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	FOREIGN KEY(machine_id) REFERENCES machines (id)
);

CREATE INDEX ix_production_records_created_at ON production_records (created_at);

CREATE INDEX ix_production_records_id ON production_records (id);

CREATE INDEX ix_production_records_tenant_code ON production_records (tenant_code);

CREATE TABLE purchase_orders (
	id SERIAL NOT NULL, 
	tenant_code VARCHAR NOT NULL, 
	po_no VARCHAR NOT NULL, 
	supplier_id INTEGER, 
	item_id INTEGER, 
	item_name VARCHAR NOT NULL, 
	order_quantity INTEGER NOT NULL, 
	received_quantity INTEGER, 
	unit VARCHAR NOT NULL, 
	expected_delivery_date DATE NOT NULL, 
	status VARCHAR, 
	notes VARCHAR, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_purchase_orders_tenant_po_no UNIQUE (tenant_code, po_no), 
	FOREIGN KEY(supplier_id) REFERENCES suppliers (id), 
	FOREIGN KEY(item_id) REFERENCES inventory_items (id)
);

CREATE INDEX ix_purchase_orders_id ON purchase_orders (id);

CREATE INDEX ix_purchase_orders_tenant_code ON purchase_orders (tenant_code);

CREATE TABLE remnants (
	id SERIAL NOT NULL, 
	tenant_code VARCHAR, 
	tag_no VARCHAR NOT NULL, 
	item_id INTEGER, 
	source_reference VARCHAR, 
	original_qty INTEGER NOT NULL, 
	remaining_qty INTEGER NOT NULL, 
	unit VARCHAR NOT NULL, 
	location VARCHAR, 
	status VARCHAR, 
	notes VARCHAR, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_remnants_tenant_tag_no UNIQUE (tenant_code, tag_no), 
	FOREIGN KEY(item_id) REFERENCES inventory_items (id)
);

CREATE INDEX ix_remnants_id ON remnants (id);

CREATE INDEX ix_remnants_tenant_code ON remnants (tenant_code);

CREATE TABLE work_orders (
	id SERIAL NOT NULL, 
	tenant_code VARCHAR NOT NULL, 
	work_order_no VARCHAR NOT NULL, 
	part_number VARCHAR NOT NULL, 
	batch_number VARCHAR NOT NULL, 
	machine_id INTEGER, 
	target_quantity INTEGER NOT NULL, 
	actual_quantity INTEGER, 
	status VARCHAR, 
	material_state VARCHAR, 
	planned_start TIMESTAMP WITHOUT TIME ZONE, 
	planned_end TIMESTAMP WITHOUT TIME ZONE, 
	completed_at TIMESTAMP WITHOUT TIME ZONE, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_work_orders_tenant_work_order_no UNIQUE (tenant_code, work_order_no), 
	FOREIGN KEY(machine_id) REFERENCES machines (id)
);

CREATE INDEX ix_work_orders_id ON work_orders (id);

CREATE INDEX ix_work_orders_tenant_code ON work_orders (tenant_code);

CREATE TABLE industrial_signals (
	id SERIAL NOT NULL, 
	tenant_code VARCHAR NOT NULL, 
	device_id INTEGER, 
	machine_id INTEGER, 
	signal_name VARCHAR NOT NULL, 
	signal_value VARCHAR NOT NULL, 
	numeric_value INTEGER, 
	unit VARCHAR, 
	quality VARCHAR, 
	source_protocol VARCHAR, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	FOREIGN KEY(device_id) REFERENCES industrial_devices (id), 
	FOREIGN KEY(machine_id) REFERENCES machines (id)
);

CREATE INDEX ix_industrial_signals_id ON industrial_signals (id);

CREATE INDEX ix_industrial_signals_tenant_code ON industrial_signals (tenant_code);

CREATE TABLE material_issue_slips (
	id SERIAL NOT NULL, 
	tenant_code VARCHAR, 
	slip_no VARCHAR NOT NULL, 
	item_id INTEGER, 
	remnant_id INTEGER, 
	work_order_ref VARCHAR, 
	requested_qty INTEGER NOT NULL, 
	issued_qty INTEGER, 
	requested_by VARCHAR NOT NULL, 
	approved_by VARCHAR, 
	status VARCHAR, 
	notes VARCHAR, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	issued_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_material_issue_slips_tenant_slip_no UNIQUE (tenant_code, slip_no), 
	FOREIGN KEY(item_id) REFERENCES inventory_items (id), 
	FOREIGN KEY(remnant_id) REFERENCES remnants (id)
);

CREATE INDEX ix_material_issue_slips_id ON material_issue_slips (id);

CREATE INDEX ix_material_issue_slips_tenant_code ON material_issue_slips (tenant_code);

CREATE TABLE plc_signal_mappings (
	id SERIAL NOT NULL, 
	tenant_code VARCHAR NOT NULL, 
	mapping_code VARCHAR NOT NULL, 
	device_id INTEGER, 
	source_signal VARCHAR NOT NULL, 
	mes_field VARCHAR NOT NULL, 
	transform_rule VARCHAR, 
	enabled VARCHAR, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_plc_signal_mappings_tenant_mapping_code UNIQUE (tenant_code, mapping_code), 
	FOREIGN KEY(device_id) REFERENCES industrial_devices (id)
);

CREATE INDEX ix_plc_signal_mappings_id ON plc_signal_mappings (id);

CREATE INDEX ix_plc_signal_mappings_tenant_code ON plc_signal_mappings (tenant_code);

CREATE TABLE production_plans (
	id SERIAL NOT NULL, 
	tenant_code VARCHAR NOT NULL, 
	plan_no VARCHAR NOT NULL, 
	work_order_id INTEGER, 
	machine_id INTEGER, 
	planned_quantity INTEGER NOT NULL, 
	actual_quantity INTEGER, 
	plan_date DATE NOT NULL, 
	shift_name VARCHAR NOT NULL, 
	status VARCHAR, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_production_plans_tenant_plan_no UNIQUE (tenant_code, plan_no), 
	FOREIGN KEY(work_order_id) REFERENCES work_orders (id), 
	FOREIGN KEY(machine_id) REFERENCES machines (id)
);

CREATE INDEX ix_production_plans_id ON production_plans (id);

CREATE INDEX ix_production_plans_tenant_code ON production_plans (tenant_code);

CREATE TABLE customer_orders (
	id SERIAL NOT NULL, 
	tenant_code VARCHAR NOT NULL, 
	order_no VARCHAR NOT NULL, 
	customer_name VARCHAR NOT NULL, 
	product_name VARCHAR NOT NULL, 
	linked_work_order_id INTEGER, 
	linked_production_plan_id INTEGER, 
	order_quantity INTEGER NOT NULL, 
	dispatched_quantity INTEGER, 
	priority VARCHAR, 
	due_date DATE NOT NULL, 
	status VARCHAR, 
	notes VARCHAR, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_customer_orders_tenant_order_no UNIQUE (tenant_code, order_no), 
	FOREIGN KEY(linked_work_order_id) REFERENCES work_orders (id), 
	FOREIGN KEY(linked_production_plan_id) REFERENCES production_plans (id)
);

CREATE INDEX ix_customer_orders_id ON customer_orders (id);

CREATE INDEX ix_customer_orders_tenant_code ON customer_orders (tenant_code);

CREATE TABLE operator_job_executions (
	id SERIAL NOT NULL, 
	tenant_code VARCHAR NOT NULL, 
	execution_no VARCHAR NOT NULL, 
	operator_name VARCHAR NOT NULL, 
	machine_id INTEGER, 
	work_order_id INTEGER, 
	production_plan_id INTEGER, 
	job_status VARCHAR, 
	good_count INTEGER, 
	rejected_count INTEGER, 
	notes VARCHAR, 
	started_at TIMESTAMP WITHOUT TIME ZONE, 
	completed_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_operator_job_executions_tenant_execution_no UNIQUE (tenant_code, execution_no), 
	FOREIGN KEY(machine_id) REFERENCES machines (id), 
	FOREIGN KEY(work_order_id) REFERENCES work_orders (id), 
	FOREIGN KEY(production_plan_id) REFERENCES production_plans (id)
);

CREATE INDEX ix_operator_job_executions_id ON operator_job_executions (id);

CREATE INDEX ix_operator_job_executions_tenant_code ON operator_job_executions (tenant_code);

CREATE TABLE production_schedules (
	id SERIAL NOT NULL, 
	tenant_code VARCHAR NOT NULL, 
	schedule_no VARCHAR NOT NULL, 
	work_order_id INTEGER, 
	production_plan_id INTEGER, 
	machine_id INTEGER, 
	shift_name VARCHAR NOT NULL, 
	scheduled_date DATE NOT NULL, 
	priority VARCHAR, 
	planned_quantity INTEGER NOT NULL, 
	estimated_minutes INTEGER, 
	status VARCHAR, 
	notes VARCHAR, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_production_schedules_tenant_schedule_no UNIQUE (tenant_code, schedule_no), 
	FOREIGN KEY(work_order_id) REFERENCES work_orders (id), 
	FOREIGN KEY(production_plan_id) REFERENCES production_plans (id), 
	FOREIGN KEY(machine_id) REFERENCES machines (id)
);

CREATE INDEX ix_production_schedules_id ON production_schedules (id);

CREATE INDEX ix_production_schedules_tenant_code ON production_schedules (tenant_code);

CREATE TABLE quality_inspections (
	id SERIAL NOT NULL, 
	tenant_code VARCHAR NOT NULL, 
	inspection_no VARCHAR NOT NULL, 
	work_order_id INTEGER, 
	production_plan_id INTEGER, 
	machine_id INTEGER, 
	inspector VARCHAR NOT NULL, 
	inspected_quantity INTEGER NOT NULL, 
	passed_quantity INTEGER, 
	failed_quantity INTEGER, 
	defect_category VARCHAR, 
	rework_quantity INTEGER, 
	scrap_quantity INTEGER, 
	status VARCHAR, 
	notes VARCHAR, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_quality_inspections_tenant_inspection_no UNIQUE (tenant_code, inspection_no), 
	FOREIGN KEY(work_order_id) REFERENCES work_orders (id), 
	FOREIGN KEY(production_plan_id) REFERENCES production_plans (id), 
	FOREIGN KEY(machine_id) REFERENCES machines (id)
);

CREATE INDEX ix_quality_inspections_created_at ON quality_inspections (created_at);

CREATE INDEX ix_quality_inspections_id ON quality_inspections (id);

CREATE INDEX ix_quality_inspections_tenant_code ON quality_inspections (tenant_code);
