"""The AMP-authored training corpus for the native copilot intent model.

WHAT THIS IS
------------
Every sentence the intent model learns from is written HERE, by AMP. No tenant
question is logged, stored or learned from - the model's consent basis is
"none required" precisely because of that. The corpus is organised in FAMILIES:
one family is one way of asking for one intent, written as

  * one or more TEMPLATES with ``{slot}`` placeholders, each slot a tuple of
    synonyms (family-local slots first, then ``SHARED_SLOTS``), and
  * at least three FREE phrasings written out in full: typos, terse forms,
    Indian-English and Hinglish shop-floor wording, the things templates miss.

``build_corpus`` expands every family with a seeded, round-robin sample of its
templates (at most ``MAX_PER_FAMILY`` sentences, free phrasings always kept).
``split_corpus`` then puts each WHOLE family in train, validation or test,
separately per label (70/15/15 of families), so no near-duplicate sentence can
sit on both sides of an evaluation.

AUTHORING PROTOCOL
------------------
1. Labels follow what each pillar in ``ai/assistant.py`` ANSWERS (read from the
   pillar functions' outputs), not which words its keyword table matches:

     help         what the copilot can do / how to use it
     trend        any comparison with an earlier period, "improving?", week on week
     inventory    stock, materials, reorder levels, stockouts, replenishment POs
     flow         work orders / jobs / WIP and the stage they are at
     shift        shift or crew attainment against target, best/worst shift
     delivery     customer (sales) orders, dispatch, on-time delivery, at-risk orders
     cost         the MONEY lost to downtime and scrap, costliest machine
     quality      first-pass yield, reject/fail rates, defects, inspections
     compliance   controlled documents, SOP reviews, approvals, audits, certificates
     maintenance  maintenance TASKS: open, overdue, PM schedule, approvals, calibration
     downtime     stoppage EVENTS over time: counts, causes, minutes lost, worst machine
     machines     the CURRENT state of machines: running, down, idle, in maintenance now
     production   output counts: units made, good units, runs, throughput, top producer
     oee          OEE and its availability/performance/quality factors, effectiveness
     briefing     "what needs attention", overall status, summaries, priorities
     __none__     small talk, off-topic, out-of-scope requests: the model has no opinion

2. The author did not open the three evaluation question files
   (test_ai_evaluation.py, test_ai_routing_holdout.py, test_ai_routing_holdout2.py)
   while writing this. That cannot be enforced, so ``leakage_report`` refuses any
   corpus sentence equal to, or with character 4-gram Jaccard >= 0.6 against, a
   question loaded from those files, and results are quoted as DIFFERENCES from
   the keyword router on the same questions.
   Disclosure: the author had read ``ai/assistant.py`` - including the keyword
   table ``_ROUTES`` - before writing this corpus. Labels were still assigned by
   intent, and no sentence was labelled or generated by running the router, but
   the corpus test split (which the author wrote) should be read as favourable to
   the model; the external question pool is the honest comparison.
3. No sentence starts with a find/locate prefix or names a specific machine: the
   router answers those BEFORE the model is consulted, so they are not training
   signal.
4. DECONTAMINATION. The first time the leakage check ran, it failed: at the
   original cap of 40 it flagged 102 of 5847 sentences (15 exact, 87 near); at
   the final cap of 20, 65 of 3629 (11 exact, 54 near). All but three were
   template renderings. They were removed without printing them or the
   questions: ``DECONTAMINATED`` lists a salted SHA-256
   prefix of each flagged sentence, produced by a script that printed only
   counts, family ids and digests, and re-run until the check was clean (70
   digests after four rounds, because each removal lets the family fill from
   renderings that may also be flagged). Expansion skips those sentences.
   Removing training sentences that resemble the test questions should make
   the external comparison harder for the model, not easier. Three families
   (trend-improving, shift-attainment, oee-overall) lost a free phrasing that
   way; each got one new free phrasing, written without knowing which one was
   removed, and the check was re-run clean. The list is exact for
   ``MAX_PER_FAMILY``: a different cap samples other renderings and must be
   re-checked (at 40 it would still flag 32).
5. SIZE. ``MAX_PER_FAMILY`` is 20 (the plan allows up to 40): at 40 the corpus
   was 5847 sentences, outside the planned 3-5k, and pure-Python full-batch
   training took about 0.5 s per epoch; at 20 it is about 3.6k (about 0.37 s per
   epoch). In a train/validation-only probe after 200 epochs, validation
   macro-F1 was 0.61 at cap 20 and 0.59 at cap 30 - indicative only, because
   the validation sentences change with the cap (the families do not).

Changing anything here changes ``corpus_sha256`` and therefore the artifact; a
changed corpus needs a rebuild, a new pin in classifier.py, and - for the
external sets, which are keyed by their own hash - it does NOT buy a fresh test.
"""
import hashlib
import itertools
import re
from dataclasses import dataclass

from ..core.artifact import canonical_json
from ..core.rng import make_rng
from ..core.split import group_split
from ..core.text_features import normalize_text
from .labels import LABELS

__all__ = [
    "CorpusError", "Family", "Example", "CORPUS_VERSION", "EXPANSION_SEED", "SPLIT_SEED",
    "MAX_PER_FAMILY", "MIN_FAMILIES_PER_LABEL", "MIN_FREE_PHRASINGS", "MAX_TEMPLATE_COMBINATIONS",
    "LEAKAGE_JACCARD", "TEST_FRAC", "VAL_FRAC", "SHARED_SLOTS", "FAMILIES", "DECONTAMINATION_SALT",
    "DECONTAMINATED", "sentence_digest", "candidate_sentences",
    "validate_families", "expand_family", "build_corpus", "corpus_sha256", "split_corpus",
    "char_ngrams", "jaccard", "leakage_report",
]

CORPUS_VERSION = "amp_ai.copilot_intent.corpus@v1"
EXPANSION_SEED = 20260917
SPLIT_SEED = 20260917
MAX_PER_FAMILY = 20
MIN_FAMILIES_PER_LABEL = 12
MIN_FREE_PHRASINGS = 3
MAX_TEMPLATE_COMBINATIONS = 5000
LEAKAGE_JACCARD = 0.6
TEST_FRAC = 0.15
VAL_FRAC = 0.15

_SLOT = re.compile(r"\{([A-Za-z_][A-Za-z0-9_]*)\}")
_FAMILY_ID = re.compile(r"[a-z0-9][a-z0-9-]*")
_FIND_PREFIXES = ("find ", "where is ", "wheres ", "locate ", "look up ", "lookup ", "search ")


class CorpusError(ValueError):
    """The corpus is malformed, would leak, or would explode combinatorially."""


@dataclass(frozen=True)
class Family:
    label: str
    family_id: str
    templates: tuple
    slots: dict
    free: tuple


@dataclass(frozen=True)
class Example:
    text: str
    label: str
    family: str


SHARED_SLOTS = {
    "NOW": ("", "right now", "now", "today", "at the moment", "currently", "as of now", "just now"),
    "PERIOD": ("", "today", "this week", "so far this week", "over the last 7 days", "yesterday",
               "in the past week"),
    "PLANT": ("the plant", "the factory", "the shop floor", "our site", "the floor", "the unit", "the works"),
    "ASK": ("", "please", "can you", "could you", "kindly"),
    "SHOW": ("show me", "tell me", "give me", "let me see", "i want to see", "i need"),
    "PLS": ("", "pls", "please", "sir", "kindly"),
}


def _f(label, family_id, templates, slots, free):
    if isinstance(templates, str):
        templates = (templates,)
    return Family(label, family_id, tuple(templates), dict(slots), tuple(free))


# =========================================================================== families
FAMILIES = (
    # ------------------------------------------------------------------ help
    _f("help", "help-what-can-you-do",
       ("what can you {do}", "what {all} can you {do}"),
       {"do": ("do", "help me with", "answer", "tell me", "do for me", "help with"),
        "all": ("else", "all", "exactly", "things", "sort of things")},
       ("wat can u do", "what are you capable of", "what are you able to answer")),
    _f("help", "help-what-can-i-ask",
       ("what {kind} of questions can i ask {you}", "what can i ask {you}"),
       {"kind": ("kind", "sort", "type", "types", "kinds"),
        "you": ("", "you", "here", "this assistant", "the copilot")},
       ("what should i be asking you", "which questions work here", "wht questions can i ask")),
    _f("help", "help-examples",
       ("{SHOW} some example questions", "{give} {me} a few sample questions"),
       {"give": ("give", "suggest", "list", "share"), "me": ("me", "us")},
       ("examples please", "sample queries?", "show a couple of things i could ask")),
    _f("help", "help-plain-help",
       ("{help}",),
       {"help": ("help", "help me", "i need help", "help please", "need some help", "can you help me",
                 "please help", "help me out", "i need some assistance", "assist me", "help needed")},
       ("helpp", "hlp", "sos how does this work")),
    _f("help", "help-how-to-use",
       ("how do i use {thing}", "how does {thing} work"),
       {"thing": ("this assistant", "the copilot", "this chat", "this bot", "the ai assistant", "this tool",
                  "amp copilot")},
       ("how do i use you", "how to use this?", "how do you work")),
    _f("help", "help-topics",
       ("which {topics} do you cover", "what {topics} can you {report_on}"),
       {"topics": ("topics", "areas", "subjects", "reports", "modules", "kpis"),
        "report_on": ("report on", "cover", "talk about", "explain")},
       ("what data do you have access to", "what information can i get from you",
        "what all things you can tell me")),
    _f("help", "help-getting-started",
       ("how do i get started {here}", "where do i {start}"),
       {"here": ("", "here", "with this", "with the copilot"), "start": ("start", "begin", "start from")},
       ("i am new here, where do i begin", "first time using this, guide me", "getting started guide")),
    _f("help", "help-capabilities-list",
       ("{SHOW} your {capabilities}", "list {your} {capabilities}"),
       {"capabilities": ("capabilities", "features", "functions", "options", "commands", "skills"),
        "your": ("your", "all your", "the")},
       ("capabilities?", "list of commands", "what features do you have")),
    _f("help", "help-dont-know-what-to-ask",
       ("i {dont} know what to ask", "not sure what {to_ask}"),
       {"dont": ("don't", "do not", "dont", "really don't"),
        "to_ask": ("to ask", "i can ask", "to ask you", "questions work")},
       ("no idea what to type here", "what do i even ask", "confused what to ask")),
    _f("help", "help-how-do-you-know",
       ("how do you {know} {this}", "where do you get your {data} from"),
       {"know": ("know", "get", "work out"), "this": ("all this", "the numbers", "this information", "your answers"),
        "data": ("data", "numbers", "information", "answers")},
       ("where does your info come from", "what is your data source", "how do u get the figures")),
    _f("help", "help-indian",
       ("kindly {explain} {what} you can do", "{explain} what all you can do"),
       {"explain": ("explain", "tell", "let me know", "share"), "what": ("what", "what all", "what exactly")},
       ("aap kya kya bata sakte ho", "what all things you can do sir", "pls tell your features")),
    _f("help", "help-what-is-this",
       ("what is this {assistant}", "what is the {assistant} for"),
       {"assistant": ("assistant", "copilot", "chatbot", "chat window", "ai helper", "bot")},
       ("what does this copilot do", "explain what you are for", "whats this chat thing")),
    _f("help", "help-can-you-answer",
       ("can you answer questions about {domain}", "do you know about {domain}"),
       {"domain": ("the plant", "my factory", "production data", "our operations", "manufacturing",
                   "the shop floor")},
       ("are you able to answer questions on my plant", "do you understand manufacturing",
        "can u answer plant questions")),

    # ------------------------------------------------------------------ trend
    _f("trend", "trend-compare-last-week",
       ("how do we compare {with} {last}", "how does this week compare {with} {last}",
        "{compare} this week {with} {last}"),
       {"with": ("with", "to", "against"), "last": ("last week", "the previous week", "the week before"),
        "compare": ("compare", "benchmark")},
       ("compare wk vs last wk", "this week or last week which is better", "how r we vs last week")),
    _f("trend", "trend-improving",
       ("is {thing} {getting}", "are {things} {getting}"),
       {"thing": ("the plant", "performance", "the factory", "oee", "the line"),
        "things": ("we", "the numbers", "our kpis", "things", "the metrics"),
        "getting": ("improving", "getting better", "getting worse", "going downhill", "on the up", "declining")},
       ("are we improving or not", "getting better or worse?", "is it improving week by week",
        "numbers trending better than before or no")),
    _f("trend", "trend-week-on-week",
       ("{show} the week on week {view}", "week over week {view}"),
       {"show": ("show", "give me", "what is", "let me see"),
        "view": ("comparison", "change", "numbers", "movement", "kpis", "performance")},
       ("wow comparison", "w-o-w numbers pls", "week-on-week report")),
    _f("trend", "trend-this-vs-last",
       ("this week {vs} last week", "{kpi} this week {vs} last week"),
       {"vs": ("vs", "versus", "compared to", "against", "or"),
        "kpi": ("oee", "output", "good rate", "losses", "performance", "scrap cost")},
       ("tw vs lw", "this wk v last wk", "current week versus previous one")),
    _f("trend", "trend-changed-since",
       ("has {kpi} {changed} since last week", "did {kpi} {change2} {from} last week"),
       {"kpi": ("oee", "the good rate", "our loss cost", "performance", "quality", "output"),
        "changed": ("changed", "gone up", "gone down", "dropped", "improved", "moved", "slipped"),
        "change2": ("go up", "go down", "drop", "improve", "change", "rise", "fall"),
        "from": ("from", "since", "compared to")},
       ("any change from last week", "oee up or down since last week?", "did we slip since last week")),
    _f("trend", "trend-direction",
       ("which way are {things} trending", "are {things} trending up or down"),
       {"things": ("things", "the numbers", "our kpis", "the metrics", "we", "results")},
       ("trending up?", "whats the trend", "show me the trend")),
    _f("trend", "trend-better-or-worse",
       ("are we {better} than {last}", "is this week {better} than {last}"),
       {"better": ("better", "worse", "better or worse", "doing better", "doing worse"),
        "last": ("last week", "the previous week", "seven days ago", "the week before")},
       ("better or worse than before?", "r we doing better than last wk", "worse than last week or what")),
    _f("trend", "trend-what-changed",
       ("what {changed} since last week", "what is different {from} last week"),
       {"changed": ("changed", "has changed", "moved", "got better", "got worse", "shifted"),
        "from": ("from", "compared to", "versus")},
       ("what's new vs last week", "any movement vs previous week", "what moved since last week")),
    _f("trend", "trend-progress",
       ("are we making progress {on} {kpi}", "how much have we {improved} {since}"),
       {"on": ("on", "with"), "kpi": ("oee", "quality", "losses", "our targets", "output"),
        "improved": ("improved", "progressed", "moved forward", "gone backwards"),
        "since": ("", "since last week", "this week", "over the past two weeks")},
       ("are we making any progress", "show me our progress over the weeks", "progress report week to week")),
    _f("trend", "trend-losses-change",
       ("did our {losses} go {up} {compared}", "are {losses} {up} on last week"),
       {"losses": ("losses", "loss costs", "costs of losses", "scrap costs"), "up": ("up", "down"),
        "compared": ("compared to last week", "vs last week", "this week versus last", "from last week")},
       ("loss cost higher than last week?", "are we losing more than last week",
        "did losses reduce from last week")),
    _f("trend", "trend-good-rate-change",
       ("is the good rate {up} {on} last week", "has {quality} {improved} week on week"),
       {"up": ("up", "down", "better", "worse"), "on": ("on", "vs", "compared to", "from"),
        "quality": ("quality", "the good rate", "yield", "first pass yield"),
        "improved": ("improved", "dropped", "changed")},
       ("good rate vs last week", "quality better than last week?", "yield change from previous week")),
    _f("trend", "trend-indian",
       ("kindly compare this week {figures} with last week", "last week vs this week {figures} {PLS}"),
       {"figures": ("figures", "numbers", "performance", "data", "report")},
       ("pichle hafte se better hai kya", "is there improvement from last week sir", "week comparison pls")),
    _f("trend", "trend-weekly-report",
       ("{show} the {weekly} {comparison}",),
       {"show": ("show", "open", "give me", "pull up"),
        "weekly": ("weekly", "week-by-week", "two-week", "last two weeks"),
        "comparison": ("comparison", "trend", "trend report", "change report", "scorecard movement")},
       ("weekly trend report", "2 week comparison", "how did the last two weeks compare")),

    # ------------------------------------------------------------------ inventory
    _f("inventory", "inv-below-reorder",
       ("which {items} are below {reorder}", "what {items} {are} at or below {reorder}"),
       {"items": ("items", "parts", "materials", "components", "skus", "raw materials", "spares"),
        "reorder": ("reorder level", "the reorder point", "minimum stock", "safety stock", "min level"),
        "are": ("are", "have fallen", "have dropped")},
       ("items below min stock?", "whats under reorder point", "list parts below safety stock")),
    _f("inventory", "inv-out-of-stock",
       ("what {is} out of stock {NOW}", "are we out of {anything}"),
       {"is": ("is", "items are", "parts are", "materials are"),
        "anything": ("anything", "any parts", "any materials", "any components", "any raw material")},
       ("stockouts?", "anything at zero stock", "which items have zero qty")),
    _f("inventory", "inv-need-to-order",
       ("what do we need to {order}", "what should {we} {order} {soon}"),
       {"order": ("reorder", "order", "buy", "purchase", "restock", "replenish"),
        "we": ("we", "i", "purchasing"), "soon": ("", "this week", "today", "next")},
       ("what to buy this week", "purchase list pls", "what needs restocking")),
    _f("inventory", "inv-stock-levels",
       ("{SHOW} {current} stock levels", "how is our stock {position}", "what does our {stock} look like"),
       {"current": ("", "current", "the current", "today's", "all"),
        "position": ("position", "situation", "looking", "doing"),
        "stock": ("stock", "inventory", "store stock", "material stock")},
       ("stock levels?", "inventory snapshot", "current inventory status")),
    _f("inventory", "inv-running-low",
       ("what are we running low on {NOW}", "which {materials} are {low}"),
       {"materials": ("materials", "parts", "items", "components", "consumables", "spares"),
        "low": ("running low", "running short", "about to run out", "nearly finished", "getting low")},
       ("anything running short?", "wat is low in stock", "which items will run out soon")),
    _f("inventory", "inv-shortage",
       ("any {material} shortage {NOW}", "is there a shortage of {material}"),
       {"material": ("material", "steel", "resin", "packaging", "pcb", "solder paste", "bearing", "fastener",
                     "copper wire")},
       ("material shortage report", "shortages we should know about", "short supply items")),
    _f("inventory", "inv-draft-pos",
       ("are there {draft} purchase orders waiting", "any {draft} pos {waiting}"),
       {"draft": ("draft", "pending", "auto-generated", "suggested", "unapproved"),
        "waiting": ("waiting", "to approve", "for review", "from the reorder agent")},
       ("did the reorder agent raise any po", "po drafts pending?", "purchase requisitions to sign off")),
    _f("inventory", "inv-enough-for",
       ("do we have enough {material} {for}", "will we run out of {material} {for}"),
       {"material": ("stock", "raw material", "steel", "packaging", "components", "resin"),
        "for": ("", "for next week", "for tomorrow", "to run the next batch", "this week")},
       ("enough material for tomorrow?", "is stock sufficient for the plan",
        "can we cover next week's material needs")),
    _f("inventory", "inv-warehouse",
       ("what's in the {store}", "{SHOW} the {store} {report}"),
       {"store": ("store", "stores", "warehouse", "godown", "stockroom"),
        "report": ("stock report", "balance", "levels", "inventory")},
       ("godown stock?", "warehouse inventory summary", "stores balance pls")),
    _f("inventory", "inv-item-qty",
       ("how many {item} do we have in stock", "how much {item} is left in {store}"),
       {"item": ("bearings", "bolts", "gaskets", "cartons", "resin", "sheet metal", "labels", "filters"),
        "store": ("stock", "the store", "the warehouse", "inventory")},
       ("qty on hand for filters", "stock count of gaskets", "how many cartons left")),
    _f("inventory", "inv-stockout-risk",
       ("which {items} are at risk of {stockout}", "{any} {stockout} risk {NOW}"),
       {"items": ("items", "parts", "materials", "skus"), "stockout": ("stockout", "running out", "stock-out"),
        "any": ("any", "is there any", "what is the")},
       ("stockout risk list", "likely to run out items", "parts at risk of shortage")),
    _f("inventory", "inv-indian",
       ("stock position {pls}", "material availability {status}"),
       {"pls": ("pls", "please", "kindly share", "sir"), "status": ("status", "report", "position", "update")},
       ("stock kitna bacha hai", "indent required for which items", "raw material ka stock batao")),
    _f("inventory", "inv-health",
       ("is {inventory} healthy", "how is {inventory} looking {NOW}"),
       {"inventory": ("inventory", "our stock", "the stock", "material stock", "stores")},
       ("inventory ok?", "inventory health check", "inventory status")),

    # ------------------------------------------------------------------ flow (work orders / WIP)
    _f("flow", "flow-wip-count",
       ("how much {wip} is on the floor {NOW}", "how many {units} are in {wip}"),
       {"wip": ("wip", "work in progress", "work-in-progress", "semi-finished stock"),
        "units": ("units", "parts", "pieces", "jobs", "orders")},
       ("wip count?", "total wip qty", "how much is in process right now")),
    _f("flow", "flow-work-order-status",
       ("{what} is the status of {the} work orders", "where are {the} work orders {at}"),
       {"what": ("what", "whats", "tell me what"), "the": ("the", "our", "all the", "open", "today's"),
        "at": ("", "at", "right now", "in the process")},
       ("wo status", "work order update pls", "status of production orders")),
    _f("flow", "flow-open-jobs",
       ("how many {jobs} are {open}",),
       {"jobs": ("jobs", "work orders", "production orders", "job cards", "batches"),
        "open": ("open", "in progress", "running", "on the floor", "still being worked on", "not finished")},
       ("open job count", "how many jobs still going", "count of unfinished work orders")),
    _f("flow", "flow-pipeline",
       ("{SHOW} the {pipeline}", "what stage are {jobs} at"),
       {"pipeline": ("pipeline", "production pipeline", "job pipeline", "work order pipeline",
                     "flow of work orders"),
        "jobs": ("the jobs", "work orders", "our orders on the floor", "the batches")},
       ("pipeline view", "stage wise work orders", "how are jobs moving through the stages")),
    _f("flow", "flow-stuck-between",
       ("which {jobs} are stuck {between}", "what is {queued} between operations"),
       {"jobs": ("jobs", "work orders", "batches", "parts"),
        "between": ("between operations", "between stations", "waiting for the next step", "in the queue"),
        "queued": ("queued", "waiting", "sitting", "piled up")},
       ("stuck jobs?", "what's waiting at the next station", "queue between ops")),
    _f("flow", "flow-finished",
       ("how many work orders {finished} {PERIOD}",),
       {"finished": ("are finished", "got completed", "were closed", "are done", "have been completed")},
       ("completed wos count", "finished jobs today?", "how many jobs closed out")),
    _f("flow", "flow-piling-up",
       ("at which {stage} is work piling up", "which {stage} has the biggest queue",
        "where are {jobs} {piling}"),
       {"stage": ("stage", "operation", "station", "step", "workcentre"),
        "jobs": ("jobs", "work orders", "batches"),
        "piling": ("piling up", "backing up", "bunching up", "getting stuck")},
       ("which step is the queue building at", "backlog by stage", "which step is holding work")),
    _f("flow", "flow-job-progress",
       ("how far along are the {jobs}", "what {progress} have the {jobs} made"),
       {"jobs": ("jobs", "work orders", "production orders", "batches", "lots"),
        "progress": ("progress", "headway")},
       ("job progress?", "% complete of open jobs", "how close are the work orders to done")),
    _f("flow", "flow-released",
       ("which {orders} are released but not started", "what has been released to the {floor}"),
       {"orders": ("work orders", "production orders", "jobs", "job cards"),
        "floor": ("floor", "shop floor", "production", "the line")},
       ("released not started list", "what's released for production", "jobs not yet begun")),
    _f("flow", "flow-indian",
       ("job card status {pls}", "kitne job card {open} hai"),
       {"pls": ("pls", "please", "sir", "kindly share"), "open": ("open", "pending", "chalu")},
       ("wip status pls", "how many pcs in wip", "pending job cards list")),
    _f("flow", "flow-half-built",
       ("how many {units} are {partial}",),
       {"units": ("units", "assemblies", "products", "parts"),
        "partial": ("partially built", "half built", "half-built", "semi finished", "unfinished",
                    "part way through")},
       ("semi finished parts count", "half done assemblies", "how much is sitting half-built")),
    _f("flow", "flow-stage-count",
       ("how many {jobs} are at {stage}", "what is in {stage} {NOW}"),
       {"jobs": ("orders", "jobs", "work orders"),
        "stage": ("assembly", "packing", "machining", "painting", "the welding stage", "final assembly")},
       ("count at packing stage", "jobs sitting in assembly", "what's queued at machining")),
    _f("flow", "flow-by-stage",
       ("split of {jobs} by stage", "{jobs} by {status}"),
       {"jobs": ("work orders", "jobs", "production orders"), "status": ("stage", "status", "progress state")},
       ("wo by stage", "count of jobs per stage", "how many not started, in progress and done")),

    # ------------------------------------------------------------------ shift
    _f("shift", "shift-attainment",
       ("what is {the} shift attainment {PERIOD}", "how did {shift} do against target"),
       {"the": ("the", "our", "today's", ""),
        "shift": ("the day shift", "the night shift", "the morning shift", "the evening shift", "a shift",
                  "b shift", "c shift", "second shift")},
       ("shift attainment?", "attainment by shift", "target achievement per shift",
        "did each shift make its numbers vs plan")),
    _f("shift", "shift-best-worst",
       ("which shift {performed} {best} {PERIOD}",),
       {"performed": ("performed", "did", "produced", "delivered"),
        "best": ("best", "worst", "the most", "the least", "better")},
       ("best shift this week", "worst performing shift", "top shift?")),
    _f("shift", "shift-hit-target",
       ("did {shift} hit {its} target", "is {shift} on target {NOW}"),
       {"shift": ("the night shift", "the day shift", "last shift", "a shift", "b shift", "the morning crew",
                  "the evening shift"),
        "its": ("its", "the", "their")},
       ("did night shift make target", "shift target met or not", "was yesterday's shift on plan")),
    _f("shift", "shift-compare",
       ("compare {a} shift {with} {b} shift",),
       {"a": ("morning", "day", "a", "first"), "b": ("night", "evening", "b", "second", "c"),
        "with": ("with", "against", "and", "vs")},
       ("day vs night shift output", "which is better morning or night shift", "shift comparison")),
    _f("shift", "shift-output-per-shift",
       ("{output} {per} shift {PERIOD}",),
       {"output": ("output", "production", "units made", "parts made", "how many units"),
        "per": ("per", "by", "for each", "in each")},
       ("shift wise output", "units produced on each shift", "per-shift production count")),
    _f("shift", "shift-crew",
       ("how did the {crew} {do}",),
       {"crew": ("crew", "night crew", "day crew", "second shift team", "b shift team", "weekend crew",
                 "evening team"),
        "do": ("do", "perform", "get on", "manage", "go")},
       ("how was the crew performance", "crew attainment", "did the team hit plan last night")),
    _f("shift", "shift-last-shift",
       ("how did the {last} shift {go}", "{summary} of the {last} shift"),
       {"last": ("last", "previous", "earlier", "night", "outgoing"),
        "go": ("go", "end", "perform", "finish up"),
        "summary": ("summary", "results", "numbers", "handover numbers")},
       ("last shift results?", "how was the previous shift", "shift handover figures")),
    _f("shift", "shift-target-vs-actual",
       ("shift target {vs} actual", "{actual} versus {plan} for each shift"),
       {"vs": ("vs", "versus", "against", "compared to"), "actual": ("actual", "actuals", "output"),
        "plan": ("plan", "target", "the target")},
       ("plan vs actual by shift", "shift targets vs achieved", "target and actual per shift")),
    _f("shift", "shift-lagging",
       ("which shift is {lagging} {PERIOD}", "is any shift {lagging}"),
       {"lagging": ("lagging", "underperforming", "falling short", "missing targets", "behind target",
                    "struggling")},
       ("weak shift?", "which crew is behind", "the shift missing its numbers")),
    _f("shift", "shift-indian",
       ("{shift} shift ka production kitna hua", "shift wise {report} {PLS}"),
       {"shift": ("a", "b", "c", "general", "night"), "report": ("production", "achievement", "report", "output")},
       ("general shift achievement", "night shift kaisa gaya", "shift achievement % pls")),
    _f("shift", "shift-current",
       ("how is the {current} shift doing", "is {current} shift on track"),
       {"current": ("current", "present", "ongoing", "this", "running")},
       ("this shift on track?", "how's the running shift", "current shift progress vs target")),
    _f("shift", "shift-shortfall",
       ("how far {below} target was {shift}", "shift {shortfall} {PERIOD}"),
       {"below": ("below", "short of", "under"),
        "shift": ("the night shift", "the day shift", "b shift", "the last shift", "the evening shift"),
        "shortfall": ("shortfall", "gap to target", "miss", "variance")},
       ("how short was the night shift", "shift gap vs target", "units short per shift")),

    # ------------------------------------------------------------------ delivery
    _f("delivery", "del-late",
       ("which {orders} are late", "how many {orders} are {late}"),
       {"orders": ("orders", "customer orders", "sales orders", "shipments", "deliveries", "consignments"),
        "late": ("late", "overdue", "past due", "delayed")},
       ("late orders?", "which customers are getting their goods late", "delayed shipments list")),
    _f("delivery", "del-on-time",
       ("what is our on-time {delivery}", "{are} delivering on time"),
       {"delivery": ("delivery", "delivery rate", "shipping rate", "delivery performance", "otd", "otif"),
        "are": ("are we", "is the plant", "is the factory")},
       ("otif %", "on time delivery?", "how punctual are our deliveries")),
    _f("delivery", "del-at-risk",
       ("which orders are at risk {of}", "which {orders} might miss their {due}"),
       {"of": ("", "of being late", "of slipping", "of missing the date"),
        "orders": ("orders", "customer orders", "deliveries", "shipments"),
        "due": ("due date", "delivery date", "ship date", "promised date")},
       ("orders at risk", "which deliveries could slip", "risky orders this week")),
    _f("delivery", "del-customer-waiting",
       ("is {customer} still waiting for {their} order", "has {customer} received {their} {goods}"),
       {"customer": ("the customer", "our client", "the buyer", "the distributor", "the oem customer"),
        "their": ("their", "the"), "goods": ("goods", "order", "shipment", "delivery")},
       ("is the client still waiting", "has the order reached the customer", "customer still waiting on goods?")),
    _f("delivery", "del-fulfilment",
       ("how much of the order book is {fulfilled}", "what is the {fulfilment} rate"),
       {"fulfilled": ("fulfilled", "fulfilled so far", "shipped", "delivered", "complete"),
        "fulfilment": ("fulfilment", "fulfillment", "order fill", "order completion")},
       ("fill rate?", "fulfilment % by units", "how much have we shipped against orders")),
    _f("delivery", "del-ship-due",
       ("what needs to {ship} {when}", "what is due for {dispatch} {when}"),
       {"ship": ("ship", "go out", "be dispatched", "be delivered"),
        "when": ("today", "tomorrow", "this week", "by friday", "next"),
        "dispatch": ("dispatch", "shipping", "delivery")},
       ("todays dispatch list", "what goes out tomorrow", "shipping schedule this week")),
    _f("delivery", "del-behind",
       ("are we behind on {customer} orders", "which {customers} are we letting down"),
       {"customer": ("customer", "client", "export", "domestic", "key account"),
        "customers": ("customers", "clients", "accounts", "buyers")},
       ("behind on any orders?", "are we letting customers down", "orders running behind")),
    _f("delivery", "del-chase-first",
       ("which order should i {chase} first", "which customer should i {call} about a delay"),
       {"chase": ("chase", "expedite", "push", "prioritise", "follow up on"),
        "call": ("call", "warn", "update", "phone")},
       ("most urgent customer order", "what to expedite first", "which order is most critical")),
    _f("delivery", "del-backlog",
       ("how big is the {order} backlog", "how many {orders} are open"),
       {"order": ("order", "sales order", "customer order"),
        "orders": ("customer orders", "sales orders", "client orders", "purchase orders from customers")},
       ("open sales orders count", "order book size", "pending customer orders")),
    _f("delivery", "del-indian",
       ("{party} ka maal kab jayega", "pending dispatch {list} {PLS}"),
       {"party": ("party", "customer", "client"), "list": ("list", "status", "report", "details")},
       ("dispatch plan for today", "which party orders are pending", "delivery status pls")),
    _f("delivery", "del-due-date",
       ("will we {make} the {due} for {customer}", "can we meet the {deadline}"),
       {"make": ("make", "hit", "meet"), "due": ("due date", "delivery date", "promised date"),
        "customer": ("the customer", "that order", "our client", "the export order"),
        "deadline": ("customer deadline", "delivery deadline", "ship date", "committed date")},
       ("will we deliver on the promised date", "can we ship in time",
        "are we going to meet the delivery commitment")),
    _f("delivery", "del-order-book",
       ("{status} of the order book", "how is the order book {looking}"),
       {"status": ("status", "state", "summary", "health"), "looking": ("looking", "doing", "shaping up")},
       ("order book?", "order book health", "orders overview")),
    _f("delivery", "del-promises",
       ("are we {keeping} our delivery {promises}",),
       {"keeping": ("keeping", "meeting", "hitting", "breaking"),
        "promises": ("promises", "commitments", "dates", "slas", "targets")},
       ("did we ship on time", "are customers getting stuff on time", "delivery commitments met?")),

    # ------------------------------------------------------------------ cost
    _f("cost", "cost-losing-money",
       ("how much {money} are we losing {PERIOD}", "how much {money} did we lose {PERIOD}"),
       {"money": ("money", "cash", "rupees", "dollars", "pounds")},
       ("money lost?", "how much are we bleeding", "total money lost this wk")),
    _f("cost", "cost-downtime-cost",
       ("what did {downtime} cost {us}", "how much is {downtime} costing {us}"),
       {"downtime": ("downtime", "the stoppages", "the breakdowns", "lost time", "machine downtime"),
        "us": ("", "us", "the business", "the company")},
       ("cost of downtime?", "downtime in money terms", "what's downtime costing in rupees")),
    _f("cost", "cost-scrap-cost",
       ("how much did {scrap} cost {PERIOD}", "what is the cost of {scrap}"),
       {"scrap": ("scrap", "rejects", "rework", "waste", "rejected parts")},
       ("scrap cost?", "value of scrap this week", "rejection cost in lakhs")),
    _f("cost", "cost-costliest-machine",
       ("which {machine} is costing us the most", "most expensive {machine} in terms of losses"),
       {"machine": ("machine", "asset", "line", "equipment", "work centre")},
       ("costliest machine", "which machine loses us most money", "biggest cost machine")),
    _f("cost", "cost-total-loss",
       ("{total} cost of losses {PERIOD}", "what's the financial impact of {our} losses"),
       {"total": ("total", "overall", "the", "combined"), "our": ("our", "the", "this week's", "all")},
       ("loss cost total", "financial impact of losses", "how expensive were our losses")),
    _f("cost", "cost-where-money",
       ("where are we {bleeding} money", "what is {draining} our money"),
       {"bleeding": ("bleeding", "losing", "wasting", "burning", "leaking"),
        "draining": ("draining", "eating", "wasting", "burning through")},
       ("which areas waste the most money", "money leaks?", "biggest money drain")),
    _f("cost", "cost-margin",
       ("how much margin are we losing to {waste}", "what is the {impact} on margin"),
       {"waste": ("waste", "downtime", "scrap", "stoppages", "rework"), "impact": ("impact", "hit", "effect")},
       ("margin impact of losses", "margin erosion from scrap", "how much margin leakage")),
    _f("cost", "cost-rupee-value",
       ("what's the {currency} value of {losses}",),
       {"currency": ("rupee", "money", "cash", "pound", "dollar"),
        "losses": ("downtime and rejection", "our losses", "lost production", "scrap and stoppages")},
       ("loss in lakhs this week", "rupees lost to breakdowns", "₹ value of losses")),
    _f("cost", "cost-expensive-problems",
       ("what are our most expensive {problems}", "which {losses} cost the most"),
       {"problems": ("problems", "issues", "losses", "failures"),
        "losses": ("losses", "stoppages", "defects", "problems")},
       ("most expensive issues", "top losses by cost", "what costs us most")),
    _f("cost", "cost-breakdown",
       ("{SHOW} the cost {breakdown} of {losses}",),
       {"breakdown": ("breakdown", "split", "analysis", "summary"),
        "losses": ("losses", "downtime and scrap", "this week's losses")},
       ("cost split downtime vs scrap", "loss costing", "costing summary")),
    _f("cost", "cost-spend-waste",
       ("how much are we spending on {waste}", "how much does {waste} cost {per} week"),
       {"waste": ("waste", "rework", "scrap", "stoppages", "idle machines"), "per": ("per", "a", "each")},
       ("spend on waste?", "weekly cost of rework", "money wasted on scrap")),
    _f("cost", "cost-financial",
       ("{financial} loss summary {PERIOD}", "{financial} impact report"),
       {"financial": ("financial", "cost", "monetary", "money")},
       ("financials of losses", "loss £ this week", "costing of losses pls")),

    # ------------------------------------------------------------------ quality
    _f("quality", "q-fpy",
       ("what is our {fpy} {PERIOD}",),
       {"fpy": ("first pass yield", "first-pass yield", "fpy", "right first time rate", "rft")},
       ("fpy?", "first time right %", "wats the fpy")),
    _f("quality", "q-reject-rate",
       ("what's the {reject} rate {PERIOD}", "{reject} percentage {PERIOD}"),
       {"reject": ("reject", "rejection", "scrap", "defect", "failure", "ng")},
       ("rejection %", "scrap rate?", "how many parts are failing")),
    _f("quality", "q-top-defect",
       ("what is the {common} defect", "what {defects} are we seeing {most}"),
       {"common": ("most common", "top", "biggest", "main", "number one"),
        "defects": ("defects", "faults", "quality issues", "failure modes"),
        "most": ("most", "most often", "this week", "")},
       ("top defect?", "pareto of defects", "most frequent fault in inspection")),
    _f("quality", "q-worst-machine",
       ("which machine has the {most} {rejects}",),
       {"most": ("most", "highest", "worst"),
        "rejects": ("rejects", "defects", "scrap", "fail rate", "rejection rate", "quality problems")},
       ("worst machine for quality", "which asset makes most bad parts", "highest defect machine")),
    _f("quality", "q-inspections",
       ("how many inspections {failed} {PERIOD}",),
       {"failed": ("failed", "passed", "were rejected", "did not pass")},
       ("failed inspections count", "qc failures", "inspection results")),
    _f("quality", "q-quality-ok",
       ("is quality {ok} {NOW}", "how is {quality} {looking}"),
       {"ok": ("ok", "good", "under control", "acceptable", "within spec"),
        "quality": ("quality", "product quality", "part quality"),
        "looking": ("looking", "doing", "holding up")},
       ("quality ok?", "any quality concerns", "quality status")),
    _f("quality", "q-bad-parts",
       ("how many {bad} parts did we {make} {PERIOD}",),
       {"bad": ("bad", "defective", "rejected", "ng", "faulty", "scrapped"),
        "make": ("make", "produce", "get")},
       ("count of ng parts", "defective pieces today", "how much scrap did we make")),
    _f("quality", "q-yield",
       ("what is the {yield} {NOW}", "{yield} {on} {line}"),
       {"yield": ("yield", "good part yield", "quality yield", "process yield"), "on": ("on", "for", "at"),
        "line": ("line 1", "the smt line", "the press shop", "assembly", "the plant")},
       ("yield?", "whats yield like", "yield % today")),
    _f("quality", "q-indian",
       ("rejection kitna {hai}", "{rework} and rejection {status}"),
       {"hai": ("hai", "hua", "hai aaj"), "rework": ("rework", "repair", "ok ng"),
        "status": ("status", "report", "details", "count")},
       ("rejection percentage today", "ng count pls", "quality report pls sir")),
    _f("quality", "q-pass-rate",
       ("what percentage of parts {pass} {qc}",),
       {"pass": ("pass", "fail", "clear"),
        "qc": ("inspection", "qc", "quality check", "final inspection", "testing")},
       ("pass rate at qc", "qc pass %", "how many pass testing")),
    _f("quality", "q-issues",
       ("any quality {issues} {NOW}", "are there quality {issues} on {line}"),
       {"issues": ("issues", "problems", "concerns", "escapes", "alerts"),
        "line": ("the line", "line 2", "assembly", "the moulding shop", "packing")},
       ("quality problems?", "any defects today", "quality alerts")),
    _f("quality", "q-defect-count",
       ("how many {defects} {PERIOD}", "{SHOW} the {defect} report"),
       {"defects": ("defects", "defects did we log", "nonconformances", "ncrs"),
        "defect": ("defect", "quality", "inspection", "ncr", "rejection")},
       ("defect log", "ncr count", "quality inspection report")),

    # ------------------------------------------------------------------ compliance
    _f("compliance", "c-overdue-review",
       ("which {documents} are overdue for review", "which {documents} need {review}"),
       {"documents": ("documents", "sops", "procedures", "work instructions", "controlled documents", "policies"),
        "review": ("review", "reviewing", "a revision", "re-approval")},
       ("docs overdue for review", "overdue sop reviews", "which procedures are out of date")),
    _f("compliance", "c-audit-ready",
       ("are we ready for the {audit}", "{is} everything in place for the {audit}"),
       {"audit": ("audit", "iso audit", "customer audit", "iatf audit", "external audit", "surveillance audit"),
        "is": ("is", "have we got")},
       ("audit readiness?", "will we pass the iso audit", "audit prep status")),
    _f("compliance", "c-unapproved",
       ("which {documents} are {unapproved}",),
       {"documents": ("documents", "sops", "procedures", "document revisions", "drawings"),
        "unapproved": ("not approved", "pending approval", "awaiting sign-off", "unsigned", "still in draft")},
       ("unapproved docs", "documents waiting for approval", "sops needing sign off")),
    _f("compliance", "c-sop-status",
       ("{status} of {our} {sops}",),
       {"status": ("status", "state", "review status", "health"), "our": ("our", "the", "all"),
        "sops": ("sops", "procedures", "standard operating procedures", "controlled documents", "quality manuals")},
       ("sop status", "procedure register", "doc control status")),
    _f("compliance", "c-due-soon",
       ("which {documents} are due for review {soon}",),
       {"documents": ("documents", "sops", "procedures", "policies", "work instructions"),
        "soon": ("soon", "this month", "next month", "in the next 30 days", "this quarter")},
       ("upcoming document reviews", "reviews due soon", "what docs expire next")),
    _f("compliance", "c-compliant",
       ("are we {compliant}", "how is our {compliance}"),
       {"compliant": ("compliant", "audit ready", "iso compliant", "in compliance"),
        "compliance": ("compliance", "compliance position", "document compliance", "regulatory compliance")},
       ("compliance status", "compliance?", "any compliance gaps")),
    _f("compliance", "c-certificates",
       ("any {certificates} expiring {soon}", "is our {cert} still valid"),
       {"certificates": ("certificates", "certifications", "licences", "permits"),
        "soon": ("soon", "this month", "this year"),
        "cert": ("iso certificate", "iatf certificate", "certification", "fire licence", "factory licence")},
       ("cert expiry dates", "certificates due for renewal", "is iso 9001 still valid")),
    _f("compliance", "c-paperwork",
       ("is the {paperwork} up to date",),
       {"paperwork": ("paperwork", "documentation", "document control", "quality paperwork", "records", "dhr")},
       ("paperwork ok?", "document control status check", "are records in order")),
    _f("compliance", "c-count",
       ("how many {documents} do we have", "{SHOW} the {register}"),
       {"documents": ("controlled documents", "sops", "procedures", "documents on file"),
        "register": ("document register", "document list", "sop register", "master list of documents")},
       ("doc count", "list of controlled docs", "master document list")),
    _f("compliance", "c-indian",
       ("sop revision {pending} list", "document review {pending} {PLS}"),
       {"pending": ("pending", "due", "overdue")},
       ("qms documents status", "sop kab review hona hai", "doc review list pls")),
    _f("compliance", "c-regulatory",
       ("any {regulatory} documents out of date", "are {safety} procedures {current}"),
       {"regulatory": ("regulatory", "safety", "environmental", "legal", "statutory"),
        "safety": ("safety", "ehs", "fire safety", "lockout"),
        "current": ("current", "up to date", "reviewed", "overdue")},
       ("statutory compliance docs", "ehs procedures overdue?", "legal documents review status")),
    _f("compliance", "c-latest-revision",
       ("are the {instructions} on the latest {revision}",),
       {"instructions": ("work instructions", "sops", "drawings", "procedures", "control plans"),
        "revision": ("revision", "version", "issue")},
       ("latest rev check", "outdated work instructions?", "old revisions in use")),

    # ------------------------------------------------------------------ maintenance
    _f("maintenance", "m-open-tasks",
       ("how many {tasks} are open", "{SHOW} the open {tasks}"),
       {"tasks": ("maintenance tasks", "maintenance jobs", "work requests", "repair tasks", "pm tasks",
                  "maintenance tickets")},
       ("open maintenance?", "maintenance task count", "how many jobs for maintenance")),
    _f("maintenance", "m-overdue-pm",
       ("which {pm} are overdue", "are any {pm} overdue"),
       {"pm": ("pms", "preventive maintenance tasks", "services", "maintenance jobs", "planned maintenance jobs",
               "lubrication tasks")},
       ("overdue pm list", "pm overdue?", "which services are late")),
    _f("maintenance", "m-due-next",
       ("which {machine} is due for {service} next", "when is the next {service} due"),
       {"machine": ("machine", "press", "asset", "compressor", "equipment"),
        "service": ("service", "servicing", "pm", "lubrication", "overhaul")},
       ("next pm due", "upcoming services", "what is due for servicing this week")),
    _f("maintenance", "m-approval",
       ("which maintenance {requests} need my approval", "any maintenance {requests} awaiting approval"),
       {"requests": ("requests", "tasks", "jobs", "repair requests", "work orders")},
       ("maintenance approvals pending", "tasks waiting for my sign off in cmms", "approve maintenance?")),
    _f("maintenance", "m-schedule",
       ("what's on the maintenance {schedule} {when}",),
       {"schedule": ("schedule", "plan", "calendar", "list"),
        "when": ("", "this week", "today", "tomorrow", "for the weekend")},
       ("maintenance plan this week", "pm schedule", "what maintenance is planned")),
    _f("maintenance", "m-backlog",
       ("how big is the maintenance {backlog}", "is the maintenance {backlog} {growing}"),
       {"backlog": ("backlog", "queue", "workload"), "growing": ("growing", "under control", "shrinking")},
       ("maintenance backlog?", "how many jobs pending for fitters", "maintenance queue length")),
    _f("maintenance", "m-team-next",
       ("what should the {team} work on {next}",),
       {"team": ("maintenance team", "fitters", "technicians", "maintenance crew", "electricians"),
        "next": ("next", "first", "today", "now")},
       ("tech priorities", "what should maintenance fix first", "fitters job list")),
    _f("maintenance", "m-cmms",
       ("{cmms} status", "open {items} in {cmms}"),
       {"cmms": ("cmms", "the cmms", "maintenance system"), "items": ("work requests", "tickets", "tasks", "jobs")},
       ("cmms?", "cmms summary", "maintenance module overview")),
    _f("maintenance", "m-pending-repairs",
       ("any pending {repair} jobs", "{repair} tickets still open"),
       {"repair": ("repair", "fix", "breakdown repair", "corrective maintenance", "electrical repair")},
       ("pending repairs?", "unfixed issues logged for maintenance", "corrective actions open for machines")),
    _f("maintenance", "m-indian",
       ("pm {pending} list", "maintenance kitna {pending} hai"),
       {"pending": ("pending", "due", "baki")},
       ("which machines pm not done", "maintenance pending sir", "pm checklist status")),
    _f("maintenance", "m-calibration",
       ("is calibration overdue on any {gauge}", "which {gauge} need calibration"),
       {"gauge": ("gauges", "instruments", "equipment", "torque wrenches", "cmm", "micrometers")},
       ("calibration due list", "overdue calibrations", "instrument calibration status")),
    _f("maintenance", "m-queue-clear",
       ("is the maintenance queue {clear}", "anything {left} for maintenance"),
       {"clear": ("clear", "empty", "up to date", "caught up"), "left": ("left", "outstanding", "pending", "still open")},
       ("maintenance all done?", "nothing pending for maintenance right", "maintenance caught up?")),

    # ------------------------------------------------------------------ downtime
    _f("downtime", "dt-events",
       ("how many {downtime} events {PERIOD}", "how many {stops} did we have {PERIOD}"),
       {"downtime": ("downtime", "stoppage", "breakdown", "stop"),
        "stops": ("stoppages", "breakdowns", "stops", "line stops", "unplanned stops")},
       ("downtime count?", "no of stoppages this week", "how many times did machines stop")),
    _f("downtime", "dt-top-cause",
       ("what is the {top} cause of {downtime}", "why {machines_stop}"),
       {"top": ("top", "main", "biggest", "most common", "number one", "leading"),
        "downtime": ("downtime", "stoppages", "breakdowns", "line stops"),
        "machines_stop": ("are the machines stopping", "do the lines keep stopping", "do we keep stopping",
                          "are the presses stopping so often")},
       ("top downtime reason", "root cause of stoppages", "main reason for breakdowns")),
    _f("downtime", "dt-most-affected",
       ("which {machine} had the most downtime {PERIOD}", "which {machine} {stopped} the most"),
       {"machine": ("machine", "asset", "line", "press", "work centre"),
        "stopped": ("stopped", "broke down", "went down", "was down")},
       ("most downtime machine", "which asset lost most hours", "worst machine for stoppages")),
    _f("downtime", "dt-why-stopped",
       ("why did the {line} stop {when}", "what stopped the {line} {when}"),
       {"line": ("line", "press", "machine", "packing line", "smt line", "conveyor"),
        "when": ("", "yesterday", "this morning", "last night", "earlier today")},
       ("why line stopped?", "reason for yesterdays stoppage", "what caused the stop on line 3")),
    _f("downtime", "dt-minutes-lost",
       ("how many {minutes} did we lose to {stoppages} {PERIOD}",),
       {"minutes": ("minutes", "hours", "production hours"),
        "stoppages": ("stoppages", "downtime", "breakdowns", "stops")},
       ("hours lost this week", "total downtime minutes", "lost time in hours")),
    _f("downtime", "dt-reasons",
       ("{list} the downtime reasons {PERIOD}", "downtime {by} reason"),
       {"list": ("list", "show", "give me", "rank"), "by": ("by", "split by", "grouped by", "per")},
       ("downtime reasons?", "reason wise downtime", "pareto of stoppage reasons")),
    _f("downtime", "dt-unplanned",
       ("how much {unplanned} downtime {PERIOD}", "how much {unplanned} downtime did we have"),
       {"unplanned": ("unplanned", "unscheduled", "planned", "total")},
       ("unplanned downtime?", "how much unscheduled stoppage", "planned vs unplanned downtime")),
    _f("downtime", "dt-how-often",
       ("how often did {machines} stop {PERIOD}", "number of {stops} {PERIOD}"),
       {"machines": ("the machines", "the line", "the presses", "equipment", "line 2"),
        "stops": ("stops", "line stops", "breakdowns", "stoppages")},
       ("stop frequency", "how frequently are we stopping", "breakdown frequency this week")),
    _f("downtime", "dt-indian",
       ("breakdown {hours} {PERIOD}", "machine stoppage report {PLS}"),
       {"hours": ("hours", "time", "minutes", "details")},
       ("line kyu ruki thi", "why line was stopped yesterday", "bd hours this week")),
    _f("downtime", "dt-lost-time",
       ("where did we lose {time} {PERIOD}", "{lost} time analysis"),
       {"time": ("time", "the most time", "production time"), "lost": ("lost", "down", "stoppage")},
       ("lost time?", "time loss report", "where are we losing hours")),
    _f("downtime", "dt-longest-stop",
       ("what was the longest {stop} {PERIOD}", "which {stop} lasted the longest"),
       {"stop": ("stoppage", "breakdown", "downtime event", "stop", "line stop")},
       ("longest breakdown?", "biggest single stoppage", "longest downtime this week")),
    _f("downtime", "dt-summary",
       ("{SHOW} {downtime}", "{downtime} summary {PERIOD}"),
       {"downtime": ("downtime", "the downtime", "stoppages", "breakdown history", "the stoppage log")},
       ("downtime?", "downtme report", "stoppage summary")),

    # ------------------------------------------------------------------ machines (current state)
    _f("machines", "mc-which-down",
       ("which {machines} are {down} {NOW}",),
       {"machines": ("machines", "assets", "presses", "lines", "equipment"),
        "down": ("down", "broken", "not running", "stopped", "offline", "out of action", "broken down")},
       ("machines down?", "whats down right now", "any machine offline")),
    _f("machines", "mc-all-running",
       ("are all {machines} {running}", "is {every} machine {running}"),
       {"machines": ("machines", "the machines", "lines", "presses", "assets"),
        "running": ("running", "up", "working", "operational", "up and running"), "every": ("every", "each")},
       ("everything running?", "all machines ok?", "all lines up")),
    _f("machines", "mc-status",
       ("{machine} status {NOW}", "what is the status of {the} {machines2}"),
       {"machine": ("machine", "equipment", "asset", "line", "fleet"), "the": ("the", "all", "our"),
        "machines2": ("machines", "equipment", "assets", "presses")},
       ("machine status", "status of machines?", "equipment state")),
    _f("machines", "mc-idle",
       ("which {machines} are idle {NOW}", "how many {machines} are {idle}"),
       {"machines": ("machines", "assets", "presses", "lines"),
        "idle": ("idle", "sitting idle", "waiting for work", "not being used")},
       ("idle machines?", "whats idle", "which equipment is waiting for jobs")),
    _f("machines", "mc-how-many-running",
       ("how many {machines} are {running} {NOW}",),
       {"machines": ("machines", "assets", "presses", "lines", "cnc machines"),
        "running": ("running", "working", "in operation", "producing")},
       ("running machine count", "no of machines working", "how many are up")),
    _f("machines", "mc-in-maintenance-now",
       ("which {machines} are {in_maint} {now2}",),
       {"machines": ("machines", "assets", "presses", "lines"),
        "in_maint": ("under maintenance", "in maintenance", "being serviced", "down for pm"),
        "now2": ("right now", "at the moment", "currently", "now")},
       ("machines being serviced right now", "what's in maintenance at the moment",
        "which assets are currently under pm")),
    _f("machines", "mc-what-doing",
       ("what are the {machines} doing {NOW}", "what is each {machine} doing"),
       {"machines": ("machines", "presses", "lines", "assets"), "machine": ("machine", "press", "line", "asset")},
       ("machine states", "live view of machines", "whats every machine up to")),
    _f("machines", "mc-anything-broken",
       ("is anything {broken} {NOW}", "are any {machines} {broken}"),
       {"broken": ("broken", "broken down", "down", "not working", "faulted"),
        "machines": ("machines", "lines", "presses", "robots")},
       ("anything down?", "any breakdown right now", "is something broken on the floor")),
    _f("machines", "mc-indian",
       ("kaunsi machine {band} hai", "machine running status {PLS}"),
       {"band": ("band", "down", "breakdown mein", "chal rahi")},
       ("how many machines are in breakdown now", "machine chal rahi hai kya", "m c status pls")),
    _f("machines", "mc-lines-up",
       ("is the {line} up", "are the {things} up and running"),
       {"line": ("whole line", "press line", "smt line", "packing line", "line 1"),
        "things": ("presses", "cnc machines", "lines", "robots", "extruders")},
       ("line up?", "is line 2 running", "are we up")),
    _f("machines", "mc-live-status",
       ("live {machine} status", "real-time {machine} {state}"),
       {"machine": ("machine", "equipment", "asset", "fleet", "shop floor"),
        "state": ("status", "state", "view", "board")},
       ("andon board", "real time status", "live status of equipment")),
    _f("machines", "mc-census",
       ("how many {machines} are {state} and how many are {state2}",),
       {"machines": ("machines", "assets", "lines"), "state": ("running", "up", "working"),
        "state2": ("down", "idle", "stopped", "broken")},
       ("running vs down count", "up down idle split", "machine census")),

    # ------------------------------------------------------------------ production
    _f("production", "p-units-made",
       ("how many {units} did we {make} {PERIOD}",),
       {"units": ("units", "parts", "pieces", "pcs", "products", "components"),
        "make": ("make", "produce", "build", "manufacture", "turn out")},
       ("units made?", "how much did we produce", "pieces produced today")),
    _f("production", "p-output",
       ("what was our {output} {PERIOD}", "{output} {PERIOD}"),
       {"output": ("output", "production output", "production", "total output", "production volume")},
       ("output?", "how much output", "prodution this week")),
    _f("production", "p-good-units",
       ("how many good {units} {PERIOD}", "{good} count {PERIOD}"),
       {"units": ("units", "parts", "pieces", "products"),
        "good": ("good units", "good parts", "ok parts", "saleable units")},
       ("good qty?", "ok pieces count", "good units vs total")),
    _f("production", "p-top-producer",
       ("which {machine} produced the most {PERIOD}", "top {producing} {machine}"),
       {"machine": ("machine", "line", "press", "asset", "cell"), "producing": ("producing", "output", "producer")},
       ("best producing machine", "highest output line", "who made the most parts")),
    _f("production", "p-throughput",
       ("what is the {throughput} {NOW}", "{rate} per hour {NOW}"),
       {"throughput": ("throughput", "production rate", "run rate", "output rate"),
        "rate": ("units", "parts", "output", "pieces")},
       ("throughput?", "how fast are we producing", "units per hour today")),
    _f("production", "p-runs",
       ("how many production {runs} {PERIOD}",),
       {"runs": ("runs", "runs did we complete", "records", "runs were logged")},
       ("production runs?", "no of runs", "run count this week")),
    _f("production", "p-volume",
       ("{total} production {volume} {PERIOD}",),
       {"total": ("total", "overall", "gross", "our"), "volume": ("volume", "quantity", "numbers", "count")},
       ("total qty produced", "gross production", "production numbers")),
    _f("production", "p-good-rate",
       ("what's the good rate {on} production {PERIOD}", "what share of {output} is good"),
       {"on": ("on", "for", "in"), "output": ("output", "production", "units made", "what we made")},
       ("good vs total ratio", "percentage good units", "good rate?")),
    _f("production", "p-indian",
       ("aaj kitna {production} hua", "production {qty} {today}"),
       {"production": ("production", "maal", "output"), "qty": ("qty", "quantity", "nos", "pcs"),
        "today": ("today", "aaj", "this week", "")},
       ("how many nos produced", "total pcs made today", "production kitna hua")),
    _f("production", "p-making-now",
       ("what are we {producing} {NOW}",),
       {"producing": ("producing", "making", "manufacturing", "building")},
       ("what's being made today", "what is in production now", "current production")),
    _f("production", "p-report",
       ("{SHOW} the production {report}", "production {report} {PERIOD}"),
       {"report": ("report", "numbers", "summary", "figures", "dashboard")},
       ("production report", "prod numbers pls", "daily production figures")),
    _f("production", "p-assembled",
       ("how many {assemblies} got {built} {PERIOD}",),
       {"assemblies": ("assemblies", "boards", "units", "kits", "castings", "mouldings"),
        "built": ("built", "assembled", "moulded", "cast", "made")},
       ("boards built today", "assemblies completed count", "how many castings poured")),

    # ------------------------------------------------------------------ oee
    _f("oee", "oee-plant",
       ("what is {the} {plant} oee {PERIOD}", "{the} oee {PERIOD}"),
       {"the": ("the", "our", ""), "plant": ("plant", "factory", "overall", "site", "line")},
       ("oee?", "whats the oee", "oee number pls")),
    _f("oee", "oee-components",
       ("what's our {component} {PERIOD}",),
       {"component": ("availability", "performance rate", "availability percentage", "performance ratio",
                      "availability and performance", "speed loss")},
       ("availability %", "performance factor?", "a p q numbers")),
    _f("oee", "oee-drag",
       ("what is {dragging} oee {down}", "{biggest} loss {factor} in oee"),
       {"dragging": ("dragging", "pulling", "holding", "killing"), "down": ("down", "back", ""),
        "biggest": ("biggest", "main", "largest"), "factor": ("factor", "driver", "component")},
       ("why is oee low", "what's hurting oee", "oee drag?")),
    _f("oee", "oee-worst-machine",
       ("which {machine} has the {lowest} oee {PERIOD}",),
       {"machine": ("machine", "line", "asset", "press", "cell"),
        "lowest": ("lowest", "worst", "poorest", "highest", "best")},
       ("worst oee machine", "lowest oee asset", "which line is least effective")),
    _f("oee", "oee-efficient",
       ("how {efficient} is {plant} {NOW}", "what is {our} equipment {effectiveness}"),
       {"efficient": ("efficient", "effective"),
        "plant": ("the plant", "the factory", "the line", "our equipment", "the shop floor"),
        "our": ("our", "the", "overall"), "effectiveness": ("effectiveness", "efficiency")},
       ("plant efficiency?", "how effective are we", "equipment efficiency %")),
    _f("oee", "oee-overall",
       ("overall equipment {effectiveness} {PERIOD}",),
       {"effectiveness": ("effectiveness", "efficiency", "effectiveness score")},
       ("overall equipment effectiveness", "oee score", "oee % this wk",
        "whole plant equipment effectiveness figure pls")),
    _f("oee", "oee-apq",
       ("{split} oee into availability performance and quality", "oee {breakdown}"),
       {"split": ("break", "split", "decompose"),
        "breakdown": ("breakdown", "components", "split", "by factor", "a p q")},
       ("apq breakdown", "oee components?", "availability performance quality split")),
    _f("oee", "oee-world-class",
       ("are we at {world} oee", "is oee above {target}"),
       {"world": ("world class", "benchmark", "target", "85 percent"),
        "target": ("85 percent", "target", "60", "our goal", "benchmark")},
       ("oee vs world class", "are we hitting oee target", "oee goal met?")),
    _f("oee", "oee-indian",
       ("oee kitna {hai}", "plant efficiency {percentage} {PLS}"),
       {"hai": ("hai", "hua", "aaya"), "percentage": ("percentage", "%", "number", "figure")},
       ("oee batao", "machine oee kya hai", "today oee pls")),
    _f("oee", "oee-avail-or-perf",
       ("are we losing more to {a} or {b}",),
       {"a": ("availability", "speed", "downtime losses"), "b": ("performance", "quality", "speed losses")},
       ("which oee factor is weakest", "is availability or performance the problem",
        "availability vs performance loss")),
    _f("oee", "oee-best-machine",
       ("which {machine} is most {effective}", "best oee {machine}"),
       {"machine": ("machine", "line", "asset", "cell"), "effective": ("effective", "efficient")},
       ("top oee machine", "most efficient line", "highest oee asset")),
    _f("oee", "oee-kpi",
       ("how effective are our {lines} {NOW}", "{effectiveness} kpi {PERIOD}"),
       {"lines": ("lines", "machines", "assets", "presses"), "effectiveness": ("effectiveness", "oee", "efficiency")},
       ("effectiveness kpi", "main efficiency kpi", "equipment effectiveness today")),

    # ------------------------------------------------------------------ briefing
    _f("briefing", "br-attention",
       ("what needs {my} attention {NOW}", "{anything} that needs {my} attention"),
       {"my": ("my", "our", "urgent", "immediate"), "anything": ("anything", "is there anything", "what is there")},
       ("needs attention?", "anything urgent", "what needs looking at")),
    _f("briefing", "br-summary",
       ("give me a {summary} of {PLANT}", "{summarise} {PLANT} for me"),
       {"summary": ("summary", "quick summary", "rundown", "snapshot", "overview"),
        "summarise": ("summarise", "summarize", "sum up", "recap")},
       ("plant summary", "sum it up for me", "quick recap of everything")),
    _f("briefing", "br-whats-wrong",
       ("what's {wrong} {NOW}", "is anything {wrong2} {NOW}"),
       {"wrong": ("wrong", "going wrong", "not okay", "the problem"),
        "wrong2": ("wrong", "going wrong", "not okay", "off")},
       ("whats wrong", "something wrong?", "tell me what's not right")),
    _f("briefing", "br-priorities",
       ("what should i {focus} {today}",),
       {"focus": ("focus on", "prioritise", "prioritize", "look at first", "worry about", "tackle first"),
        "today": ("", "today", "this morning", "this shift", "now")},
       ("top priorities?", "priorities for today", "where should i focus")),
    _f("briefing", "br-how-doing",
       ("how is {PLANT} doing {NOW}", "how are things {on} {PLANT}"),
       {"on": ("on", "at", "in")},
       ("hows it going", "how are we doing", "how's the factory")),
    _f("briefing", "br-status-update",
       ("{quick} status update", "{quick} update on {everything}"),
       {"quick": ("", "quick", "overall", "general", "full"),
        "everything": ("everything", "the plant", "operations", "the site")},
       ("status?", "update pls", "sitrep")),
    _f("briefing", "br-issues",
       ("any {issues} {NOW}", "are there {issues} i should know about"),
       {"issues": ("issues", "problems", "concerns", "red flags", "surprises")},
       ("problems?", "anything i should know", "any bad news")),
    _f("briefing", "br-overview",
       ("{overview} of {PLANT}", "{SHOW} the {overview}"),
       {"overview": ("overview", "big picture", "general picture", "overall picture", "plant overview")},
       ("big picture?", "helicopter view of operations", "overall view pls")),
    _f("briefing", "br-brief-me",
       ("{brief}", "{morning} briefing"),
       {"brief": ("brief me", "catch me up", "fill me in", "update me", "bring me up to speed",
                  "get me up to speed"),
        "morning": ("morning", "daily", "today's", "the", "start of day")},
       ("daily brief", "morning update pls", "what did i miss")),
    _f("briefing", "br-fires",
       ("any fires to {put} out", "what's on fire {NOW}"),
       {"put": ("put", "fight", "stamp")},
       ("firefighting list", "any emergencies", "what's burning")),
    _f("briefing", "br-happening",
       ("what's happening {on} {PLANT}", "what is going on {NOW}"),
       {"on": ("on", "in", "at", "across")},
       ("whats happening", "what's going on", "wassup on the floor")),
    _f("briefing", "br-indian",
       ("kya chal raha hai {plant}", "overall status {PLS}"),
       {"plant": ("plant mein", "factory mein", "floor pe", "")},
       ("all ok in plant?", "sab theek hai kya", "everything fine sir?")),
    _f("briefing", "br-alerts",
       ("any {alerts} {NOW}", "{SHOW} the {alerts}"),
       {"alerts": ("alerts", "warnings", "alarms", "exceptions", "flags")},
       ("alerts?", "open alerts", "what is flagged right now")),

    # ------------------------------------------------------------------ __none__
    _f("__none__", "none-greeting",
       ("{hi}", "{hi} {there}"),
       {"hi": ("hi", "hello", "hey", "good morning", "good evening", "namaste", "yo"),
        "there": ("there", "copilot", "bot", "team", "buddy")},
       ("hii", "hello?", "gm")),
    _f("__none__", "none-thanks",
       ("{thanks}", "{thanks} {extra}"),
       {"thanks": ("thanks", "thank you", "cheers", "ok thanks", "great thanks", "cool"),
        "extra": ("a lot", "for that", "mate", "so much")},
       ("thx", "ok", "got it")),
    _f("__none__", "none-weather",
       ("what's the weather {when}", "will it rain {when}"),
       {"when": ("today", "tomorrow", "this weekend", "in pune", "in chennai", "later")},
       ("weather?", "is it hot outside", "temperature outside now")),
    _f("__none__", "none-jokes",
       ("tell me a {joke}", "say something {funny}"),
       {"joke": ("joke", "funny story", "riddle", "fun fact"), "funny": ("funny", "interesting", "nice", "random")},
       ("joke pls", "entertain me", "sing a song")),
    _f("__none__", "none-small-talk",
       ("how are {you}", "{are} you {human}"),
       {"you": ("you", "you doing", "you today", "things with you"), "are": ("are", "r"),
        "human": ("human", "a robot", "real", "sentient", "a person")},
       ("whats your name", "do you sleep", "who made you")),
    _f("__none__", "none-general-knowledge",
       ("what is the capital of {country}", "who {won} the {match}"),
       {"country": ("france", "japan", "australia", "brazil", "kenya"), "won": ("won", "is winning"),
        "match": ("match", "cricket match", "world cup", "football game", "election")},
       ("who is the prime minister", "how tall is mount everest", "when did world war 2 end")),
    _f("__none__", "none-coding",
       ("write a {lang} {thing} to {task}",),
       {"lang": ("python", "javascript", "sql", "excel"), "thing": ("script", "function", "macro", "program"),
        "task": ("sort a list", "send emails", "parse a csv", "reverse a string")},
       ("fix my code", "how do i center a div", "explain recursion")),
    _f("__none__", "none-hr-admin",
       ("how do i apply for {leave}", "when is {payday}"),
       {"leave": ("leave", "sick leave", "annual leave", "a holiday", "overtime pay"),
        "payday": ("payday", "the next holiday", "the diwali bonus", "salary credited", "the team party")},
       ("my payslip is wrong", "hr contact number", "leave balance?")),
    _f("__none__", "none-canteen",
       ("what's for {meal} {when}", "is the {place} open"),
       {"meal": ("lunch", "dinner", "breakfast", "tea"), "when": ("", "today", "in the canteen", "tomorrow"),
        "place": ("canteen", "cafeteria", "gym", "medical room")},
       ("canteen menu", "tea break time?", "where can i get coffee")),
    _f("__none__", "none-gibberish",
       ("{junk}",),
       {"junk": ("asdf", "qwerty", "lorem ipsum", "jjjjj", "test", "testing 123", "xyz", "ok ok ok", "hmm",
                 "blah blah")},
       ("asdfghjkl", "zzz", "123456")),
    _f("__none__", "none-math",
       ("what is {a} times {b}", "convert {x} to {unit}"),
       {"a": ("17", "12", "250", "3.5"), "b": ("23", "8", "4", "19"),
        "x": ("5 inches", "20 kg", "100 fahrenheit", "3 miles"), "unit": ("mm", "pounds", "celsius", "km")},
       ("square root of 144", "2+2", "15 percent of 800")),
    _f("__none__", "none-actions",
       ("{send} an email to {who}", "book a {thing} {when}"),
       {"send": ("send", "draft", "write"), "who": ("the supplier", "my boss", "hr", "the team"),
        "thing": ("meeting room", "cab", "flight", "table"), "when": ("for tomorrow", "at 3pm", "for monday", "")},
       ("set a reminder for 5pm", "call my wife", "schedule a meeting with the team")),
    _f("__none__", "none-news-markets",
       ("how is the {market} {today}", "what is the {market} {doing}", "latest {news}"),
       {"market": ("share market", "sensex", "nifty", "stock market", "gold price"),
        "today": ("today", "now", "this week", ""), "doing": ("doing", "at", "trading at"),
        "news": ("news", "headlines", "cricket score", "sports news")},
       ("share price of tata motors", "bitcoin price", "any news today")),
    _f("__none__", "none-it-support",
       ("{my} {device} is not working", "what is the {wifi} password"),
       {"my": ("my", "the office"), "device": ("laptop", "printer", "email", "phone", "vpn"),
        "wifi": ("wifi", "wi-fi", "guest wifi", "system")},
       ("reset my password", "how do i log out", "screen is frozen")),
)


# =========================================================================== decontamination
DECONTAMINATION_SALT = "amp_ai.copilot_intent.decontaminated|"
# sentence_digest() of every corpus sentence the leakage check flagged (see AUTHORING PROTOCOL 4).
DECONTAMINATED = frozenset({
    "02f776062d036c6f", "0f17c59ff930861d", "1177d620868871cd", "1aa98037e74def72", "1c8a5808cb4f425c",
    "1d47ec4fed6857eb", "29ce777da0e3d8c9", "2b0626757949a9cc", "2cb32c9f496068eb", "38f1d62e28959c98",
    "3dd422cb133a0788", "44a00241a30fb29c", "452e2f2bb0907e3b", "4614393380eb1426", "46af4b96721466ef",
    "47ac9ee86edc1f0a", "4b1cac6c73ffe932", "5317a89b3821124e", "54267f14bebcc822", "562cf7fb460c544c",
    "5c1af765ffc3592d", "5d4441646e3537ef", "5e7325f25a710d4c", "60a11116d2ea15a6", "652bac54b3285e64",
    "686f336916572160", "6877fb63ad3a248c", "6966e5d384374876", "69a485179c6bd84e", "6acae17629eba004",
    "765d1adc7661864f", "7713fd8e42d3a2c3", "7b7c3c580f51d19f", "92c6798b9053a822", "931869a8f98e99c7",
    "95ef7eebd0d5f54c", "9690ae7b8b148a50", "a022d5e8bacf5dcc", "a246dbb4615da957", "a318266e3553f5b9",
    "a751779a1186bbf9", "afa1d2972e24fdd9", "b091a0743545047a", "b14e12bdb6db413e", "b819a74904aae34c",
    "b93951098f31ea84", "b9ca82a838cf71f4", "bb91d97bc2e33d16", "be534589fd41bb79", "c560cd0ae66def48",
    "c5c0923a2fb17600", "c88edc1f8c4a5481", "c8d2ed47c377ef5b", "cc9adaa253ebc379", "cedab216f958009e",
    "d00987a40fdbc56c", "d01ff6af4fc9f8c9", "d12630f1487dbef2", "dbdf35552e171ce8", "e0e5d8bcd2c17512",
    "e51c6c582fd39930", "e6ea0e6460b678b2", "e7a2349d40ff19ff", "e87aed4d7188627c", "ec493c84b5f88b92",
    "ed321567c47f1600", "f375f380ef1747a0", "f6ad6ff374cd1011", "f87d4e58598f3e2e", "fc6336463d01f4a7",
})


def sentence_digest(text) -> str:
    """16 hex characters of SHA-256(salt + normalize_text(text)): names a sentence without spelling it."""
    return hashlib.sha256((DECONTAMINATION_SALT + normalize_text(text)).encode("utf-8")).hexdigest()[:16]


# =========================================================================== validation and expansion
def _slot_values(family, name):
    if name in family.slots:
        return family.slots[name]
    if name in SHARED_SLOTS:
        return SHARED_SLOTS[name]
    raise CorpusError(f"family {family.family_id}: template slot {{{name}}} is not defined")


def _template_slots(template):
    names = []
    for name in _SLOT.findall(template):
        if name not in names:
            names.append(name)
    return names


def _combinations(family, template):
    total = 1
    for name in _template_slots(template):
        total *= len(_slot_values(family, name))
    return total


def validate_families(families=None, *, decontaminated=None) -> None:
    """Raise CorpusError unless every family is well formed and every label is covered.

    A family must keep MIN_FREE_PHRASINGS free phrasings AFTER decontamination.
    """
    families = FAMILIES if families is None else tuple(families)
    decontaminated = DECONTAMINATED if decontaminated is None else frozenset(decontaminated)
    seen_ids = set()
    per_label = {label: 0 for label in LABELS}
    for fam in families:
        if not isinstance(fam, Family):
            raise CorpusError(f"not a Family: {fam!r}")
        if not isinstance(fam.family_id, str) or not _FAMILY_ID.fullmatch(fam.family_id):
            raise CorpusError(f"family id {fam.family_id!r} must be lowercase letters, digits and '-'")
        if fam.family_id in seen_ids:
            raise CorpusError(f"duplicate family id {fam.family_id!r}")
        seen_ids.add(fam.family_id)
        if fam.label not in per_label:
            raise CorpusError(f"family {fam.family_id}: label {fam.label!r} is not in LABELS")
        per_label[fam.label] += 1
        if not fam.templates or not all(isinstance(t, str) and t.strip() for t in fam.templates):
            raise CorpusError(f"family {fam.family_id}: needs at least one non-empty template")
        if len(fam.free) < MIN_FREE_PHRASINGS or not all(isinstance(t, str) and normalize_text(t) for t in fam.free):
            raise CorpusError(f"family {fam.family_id}: needs at least {MIN_FREE_PHRASINGS} non-empty free phrasings")
        surviving = [t for t in fam.free if sentence_digest(t) not in decontaminated]
        if len(surviving) < MIN_FREE_PHRASINGS:
            raise CorpusError(f"family {fam.family_id}: only {len(surviving)} free phrasings survive "
                              f"decontamination (needs {MIN_FREE_PHRASINGS})")
        for name, values in fam.slots.items():
            if not isinstance(values, tuple) or not values or not all(isinstance(v, str) for v in values):
                raise CorpusError(f"family {fam.family_id}: slot {name!r} must be a non-empty tuple of strings")
        for template in fam.templates:
            count = _combinations(fam, template)
            if count > MAX_TEMPLATE_COMBINATIONS:
                raise CorpusError(f"family {fam.family_id}: template has {count} combinations "
                                  f"(> {MAX_TEMPLATE_COMBINATIONS})")
    thin = {label: n for label, n in per_label.items() if n < MIN_FAMILIES_PER_LABEL}
    if thin:
        raise CorpusError(f"labels with fewer than {MIN_FAMILIES_PER_LABEL} families: {thin}")


def _render(template, mapping):
    return " ".join(_SLOT.sub(lambda m: mapping[m.group(1)], template).split())


def candidate_sentences(family) -> list:
    """Every sentence the family could contribute before sampling and decontamination: free phrasings,
    then every rendering of every template (in template order)."""
    out = list(family.free)
    for template in family.templates:
        count = _combinations(family, template)
        if count > MAX_TEMPLATE_COMBINATIONS:
            raise CorpusError(f"family {family.family_id}: template has {count} combinations "
                              f"(> {MAX_TEMPLATE_COMBINATIONS})")
        names = _template_slots(template)
        for combo in itertools.product(*(_slot_values(family, name) for name in names)):
            out.append(_render(template, dict(zip(names, combo))))
    return out


def expand_family(family, *, seed, cap, decontaminated=None) -> list:
    """Free phrasings plus a seeded round-robin sample of template expansions, at most ``cap`` sentences.

    Decontaminated sentences are skipped (free phrasings included); the family fills from its other
    renderings.
    """
    if isinstance(cap, bool) or not isinstance(cap, int) or cap < len(family.free):
        raise CorpusError(f"family {family.family_id}: cap {cap!r} is smaller than its free phrasings")
    decontaminated = DECONTAMINATED if decontaminated is None else frozenset(decontaminated)
    rng = make_rng(seed, "corpus", family.family_id)
    per_template = []
    for template in family.templates:
        count = _combinations(family, template)
        if count > MAX_TEMPLATE_COMBINATIONS:
            raise CorpusError(f"family {family.family_id}: template has {count} combinations "
                              f"(> {MAX_TEMPLATE_COMBINATIONS})")
        names = _template_slots(template)
        rendered, keys = [], set()
        for combo in itertools.product(*(_slot_values(family, name) for name in names)):
            text = _render(template, dict(zip(names, combo)))
            key = normalize_text(text)
            if key and key not in keys:
                keys.add(key)
                rendered.append(text)
        rng.shuffle(rendered)
        per_template.append(rendered)

    out, seen = [], set()

    def add(text):
        key = normalize_text(text)
        if key and key not in seen and sentence_digest(key) not in decontaminated:
            seen.add(key)
            out.append(Example(text, family.label, family.family_id))

    for text in family.free:
        add(text)
    position = 0
    while len(out) < cap and any(position < len(r) for r in per_template):
        for rendered in per_template:
            if position < len(rendered) and len(out) < cap:
                add(rendered[position])
        position += 1
    return out


def build_corpus(*, seed=EXPANSION_SEED, cap=MAX_PER_FAMILY, families=None, decontaminated=None) -> list:
    """Every family expanded, in family order. A sentence already produced by an earlier family is
    dropped; a sentence claimed by two DIFFERENT labels is a CorpusError."""
    families = FAMILIES if families is None else tuple(families)
    decontaminated = DECONTAMINATED if decontaminated is None else frozenset(decontaminated)
    validate_families(families, decontaminated=decontaminated)
    owner = {}
    corpus = []
    for fam in families:
        for ex in expand_family(fam, seed=seed, cap=cap, decontaminated=decontaminated):
            key = normalize_text(ex.text)
            if key in owner:
                label, family_id = owner[key]
                if label != ex.label:
                    raise CorpusError(f"sentence claimed by {family_id} ({label}) and {fam.family_id} ({ex.label})")
                continue
            owner[key] = (ex.label, ex.family)
            corpus.append(ex)
    return corpus


def corpus_sha256(examples) -> str:
    """SHA-256 of the canonical JSON of (corpus version, [family, label, text] for every example)."""
    body = {"corpus_version": CORPUS_VERSION, "examples": [[e.family, e.label, e.text] for e in examples]}
    return hashlib.sha256(canonical_json(body)).hexdigest()


# =========================================================================== split
def split_corpus(examples, *, seed=SPLIT_SEED, test_frac=TEST_FRAC, val_frac=VAL_FRAC):
    """(train, val, test): whole families, split separately for each label so every label is in every split."""
    by_label = {}
    for ex in examples:
        by_label.setdefault(ex.label, []).append(ex)
    train, val, test = [], [], []
    for label in LABELS:
        items = by_label.get(label)
        if not items:
            raise CorpusError(f"no examples for label {label!r}")
        label_seed = make_rng(seed, "split", label).randrange(2 ** 31)
        tr, va, te = group_split(items, lambda e: e.family, test_frac=test_frac, val_frac=val_frac,
                                 seed=label_seed)
        train.extend(tr)
        val.extend(va)
        test.extend(te)
    return train, val, test


# =========================================================================== leakage
def char_ngrams(text, n=4) -> frozenset:
    """Character n-grams of ``" " + normalize_text(text) + " "``."""
    padded = f" {normalize_text(text)} "
    if len(padded) <= n:
        return frozenset([padded])
    return frozenset(padded[i:i + n] for i in range(len(padded) - n + 1))


def jaccard(a, b) -> float:
    union = len(a | b)
    return len(a & b) / union if union else 0.0


def leakage_report(corpus_texts, questions, *, threshold=LEAKAGE_JACCARD) -> dict:
    """Count corpus sentences that copy (exactly, or char-4-gram Jaccard >= threshold) an evaluation question.

    Returns counts and the INDICES of offending corpus sentences - never question text, so the
    corpus author can fix their own sentence without reading the evaluation set.
    """
    q_norm = sorted({normalize_text(q) for q in questions} - {""})
    if not q_norm:
        raise CorpusError("no evaluation questions to check against: a leakage check that loads nothing "
                          "would report all-clear")
    q_set = set(q_norm)
    q_grams = [(char_ngrams(q), q) for q in q_norm]
    exact, near, flagged = 0, 0, []
    checked = 0
    for index, text in enumerate(corpus_texts):
        key = normalize_text(text)
        checked += 1
        if key in q_set:
            exact += 1
            flagged.append(index)
            continue
        grams = char_ngrams(key)
        size = len(grams)
        for q_gram, _q in q_grams:
            other = len(q_gram)
            if min(size, other) < threshold * max(size, other):
                continue
            if jaccard(grams, q_gram) >= threshold:
                near += 1
                flagged.append(index)
                break
    return {"questions_checked": len(q_norm), "corpus_sentences_checked": checked, "exact": exact,
            "near": near, "threshold": threshold, "flagged_indices": flagged}
