import { describe, expect, it } from "vitest";

import { fallbackOee, readMachineOee } from "./oee";
import type { ExecutiveMachineOee } from "./phase15-types";

/**
 * The machine cards on the dashboard used to print
 * `utilization / 100 * 0.9 * 0.95 * 100` and label it "Estimated OEE".
 *
 * That number is a linear rescale of the utilization shown directly above it -
 * it carries no information the reader did not already have, and it is blind to
 * the two things OEE exists to expose. Performance and quality were literal
 * constants. A machine scrapping 40% of its output showed the same 68% as one
 * scrapping nothing.
 *
 * The real figures were already on the page: `/analytics/executive-oee` returns
 * measured availability/performance/quality/oee per machine, computed from
 * production records, quality inspections and parsed downtime, and the
 * dashboard already fetched it for the exec section. The card just was not
 * reading it.
 *
 * The estimate survives as a labelled fallback for machines with no production
 * data, which is the same thing the backend does
 * (`analytics_engine.calculate_fallback_oee`).
 */

const row = (over: Partial<ExecutiveMachineOee> = {}): ExecutiveMachineOee => ({
  machine_id: 1,
  machine_name: "CNC-01",
  status: "Running",
  availability: 80,
  performance: 78,
  quality: 90,
  oee: 56,
  downtime_minutes: 96,
  total_count: 600,
  good_count: 540,
  rejected_count: 60,
  utilization: 80,
  ...over,
});

describe("readMachineOee", () => {
  it("prefers the measured figure over the estimate", () => {
    // The headline case, with numbers from backend/analytics_engine.py: a
    // machine at 80% utilization running its planned window but scrapping 40%
    // of its output measures 38%. The card showed 68% - it could not see the
    // scrap at all.
    const scrapping = row({ quality: 60, oee: 38 });

    expect(fallbackOee(80)).toBe(68); // what the card used to print
    expect(readMachineOee(1, [scrapping], 80)).toEqual({ oee: 38, measured: true });
  });

  it("distinguishes two machines the estimate could not tell apart", () => {
    const clean = row({ machine_id: 1, quality: 99, oee: 62 });
    const scrapping = row({ machine_id: 2, quality: 60, oee: 38 });

    // Same utilization, so the old card printed 68% for both.
    expect(fallbackOee(80)).toBe(68);

    expect(readMachineOee(1, [clean, scrapping], 80)?.oee).toBe(62);
    expect(readMachineOee(2, [clean, scrapping], 80)?.oee).toBe(38);
  });

  it("falls back to the estimate for a machine with no measured row", () => {
    // A machine that has never reported production has nothing to measure. The
    // estimate is still the honest best available - but it must be labelled as
    // one, which is what `measured: false` drives.
    expect(readMachineOee(99, [row()], 40)).toEqual({ oee: 34, measured: false });
  });

  it("falls back while the ranking is still loading, rather than showing nothing", () => {
    expect(readMachineOee(1, null, 40)).toEqual({ oee: 34, measured: false });
    expect(readMachineOee(1, undefined, 40)).toEqual({ oee: 34, measured: false });
    expect(readMachineOee(1, [], 40)).toEqual({ oee: 34, measured: false });
  });

  it("reports nothing at all when there is no measurement AND no utilization", () => {
    // `Machine.utilization` is a nullable Integer column. Guessing 0% for an
    // unset reading would be inventing a number - the card renders a dash.
    expect(readMachineOee(1, [], null)).toBeNull();
    expect(readMachineOee(1, [], undefined)).toBeNull();
    expect(readMachineOee(1, [], Number.NaN)).toBeNull();
  });

  it("still reports a measured zero, which is a real reading", () => {
    // A dead machine measures 0. That must render as 0%, not as "no data" - the
    // difference between "broken" and "unknown" is the whole point.
    expect(readMachineOee(1, [row({ oee: 0 })], 80)).toEqual({ oee: 0, measured: true });
  });
});

describe("fallbackOee", () => {
  // Generated by running backend/analytics_engine.py:calculate_fallback_oee over
  // every integer utilization. `Machine.utilization` is an Integer column, so
  // this is complete coverage of the fallback's domain - the two sides cannot
  // drift the way the duration parsers did (see lib/duration.ts).
  const BACKEND = [
    0, 1, 2, 3, 3, 4, 5, 6, 7, 8, 9, 9, 10, 11, 12, 13, 14, 15, 15, 16, 17, 18, 19, 20, 21, 21,
    22, 23, 24, 25, 26, 27, 27, 28, 29, 30, 31, 32, 32, 33, 34, 35, 36, 37, 38, 38, 39, 40, 41,
    42, 43, 44, 44, 45, 46, 47, 48, 49, 50, 50, 51, 52, 53, 54, 55, 56, 56, 57, 58, 59, 60, 61,
    62, 62, 63, 64, 65, 66, 67, 68, 68, 69, 70, 71, 72, 73, 74, 74, 75, 76, 77, 78, 79, 80, 80,
    81, 82, 83, 84, 85, 86,
  ];

  it("agrees with the backend for every possible utilization", () => {
    expect(BACKEND).toHaveLength(101);
    for (let u = 0; u <= 100; u += 1) {
      expect(fallbackOee(u)).toBe(BACKEND[u]);
    }
  });
});
